### ISSUE TITLE
Issues extending base type Maybe<never>

### ISSUE THREAD

**Issue by evanrooijen** [gigobyte/purify#107]
The following issues popped up after upgrading from 0.12.x to 0.13.x:

Property 'extract' in type 'Nothing' is not assignable to the same property in base type 'Maybe<never>'.
```
  Type '() => this extends AlwaysJust ? never : undefined' is not assignable to type '() => this extends AlwaysJust ? never : never'.
    Type 'this extends AlwaysJust ? never : undefined' is not assignable to type 'this extends AlwaysJust ? never : never'.
      Type 'undefined' is not assignable to type 'never'.
```

Property 'extractNullable' in type 'Nothing' is not assignable to the same property in base type 'Maybe<never>'.

  ```
Type '() => this extends AlwaysJust ? never : null' is not assignable to type '() => this extends AlwaysJust ? never : never'.
    Type 'this extends AlwaysJust ? never : null' is not assignable to type 'this extends AlwaysJust ? never : never'.
      Type 'null' is not assignable to type 'never'.
```

**Comment by gigobyte** [comment]
Can you post a code snippet that will help me reproduce this issue?

**Comment by evanrooijen** [comment]
Currently running typescript 3.4.5

**Comment by gigobyte** [comment]
Can you provide me with a [SSCCE](http://sscce.org/)?

**Comment by BrendanBall** [comment]
@gigobyte I'm getting the same error just running the example from the docs
```
Right(5).extract()
```
See the exact environment at https://github.com/BrendanBall/purify-ts-bug/commit/54d95411b612ac21c3f29a8d09d63e65da027fc7
node v12.10.0

**Comment by gigobyte** [comment]
@BrendanBall Thank you, I'll try to fix this issue soon.

**Comment by gigobyte** [comment]
I'm having trouble fixing this issue, in the meantime you can add `"skipLibCheck": true` in your tsconfig file to compile your projects.

**Comment by gigobyte** [comment]
I've published a new version
