### ISSUE TITLE
Improve toString for debugging

### ISSUE THREAD

**Issue by BrendanBall** [gigobyte/purify#112]
Hi, I'm trying out your library, and playing around with it I'm having difficulty debugging with logs. Take for example an `Either` of value `Right({foo: 'bar', bar: { baz: 'baz'}})`. When this is stringified it comes out as `Right([object Object])` which is quite useless. It would be nice if it can rather JSON stringify that. For example currently I'm doing 
```
Object.prototype.toString = function() {
    return JSON.stringify(this, null, 2)
}
console.log(`${Right({foo: 'bar', bar: { baz: 'baz'}})}`)
```
which prints: 
```
Right({
  "foo": "bar",
  "bar": {
    "baz": "baz"
  }
})
```
I don't want to override Object.prototype.toString so it would be awesome if this library can be improved in this way.

**Comment by gigobyte** [comment]
That's definitely something that can be improved, thanks for the suggestion.

**Comment by gigobyte** [comment]
After giving it some thought, is this behaviour wanted? For example `({a: 5}).toString()` results in `"[object Object]"` as well. Maybe you can JSON.stringify the object you're logging, in that case the result will be closer to what you expected.

**Comment by BrendanBall** [comment]
```
console.log(JSON.stringify(Left(5)))
console.log(JSON.stringify(Right(5)))
```
both just print
```
5
5
```
and if you don't either `JSON.stringify` or `toString` then it prints out the entire class which is even worse.

**Comment by gigobyte** [comment]
I've published a new version.
