### ISSUE TITLE
are Either types correct?

### ISSUE THREAD

**Issue by overflowz** [gigobyte/purify#115]
For some reason, I cannot chain left to right and left to left (type errors).

```ts
const r1 = () => right(1);
const l1 = () => left('woops');
const l2 = () => left(/woo/);
const rl = () => Math.random() > 0.5 ? left('woo') : right('yay'); // could be the case.

r1().chain(l1); // error
l1().chain(l2); // error
```

Any thoughts?

**Comment by gigobyte** [comment]
You have to help the compiler a bit, because if you write `Right(1)` it can't know the "left" type parameter of the Either type so the return type of your `r1` function is `Either<never, number>` and then TypeScript just stumbles.

Regarding the second line - `l1().chain(l2)`, I believe the types are wrong, yes. Thank you for reporting this issue!

**Comment by overflowz** [comment]
Yeah, my bad on that :) Also IMO this is a bit confusing (isn't it?):
```ts
const r1 = () => right<number, string>(1);
const l1 = () => left<string, number>('woops');
```

Right's first generic type is for right while left's is for the left, thus it's a bit confusing for me ;p

**Comment by gigobyte** [comment]
You can write
```js
const r1 = (): Either<string, number> => right(1);
const l1 = (): Either<string, number> => left('woops');
```
instead, it's a good practice to add type annotations to your functions anyway.

By the way, I tried your code with fp-ts and it seems to error as well, really interesting:
```js
import { left, right, chain } from 'fp-ts/lib/Either'

const r1 = () => right(1)
const l1 = () => left('woops')
const l2 = () => left(/woo/)
const rl = () => (Math.random() > 0.5 ? left('woo') : right('yay')) // could be the case.

/* Argument of type '() => Either<never, number>' is not assignable to parameter of type 'Either<string, unknown>'. Type '() => Either<never, number>' is missing the following properties from type 'Right<unknown>': _tag, rightts(2345) */
chain(l1)(r1)
/* Argument of type '() => Either<string, never>' is not assignable to parameter of type 'Either<RegExp, unknown>'. Type '() => Either<string, never>' is missing the following properties from type 'Left<RegExp>': _tag, leftts(2345) */
chain(l2)(l1)
```

**Comment by overflowz** [comment]
Damn, you're right! Sorry ;p I used Right/Left instead of Either type.
As for those types, yeah. I think it needs overloading but not certainly sure. I played with that for a bit but without any luck.

**Comment by overflowz** [comment]
But I think that because they are two different types while it checks only for one. I think that is the right approach to have tho. You have to explicitly tell what they are going to return and when left types are mismatched (does not matter when) they should not be allowed to.

**Comment by gigobyte** [comment]
I'm going to play around with your examples either way, hopefully I can come up with some better types so that the developer experience is smoother.
