### ISSUE TITLE
just(T) should returns type Maybe<T>

### ISSUE THREAD

**Issue by imcotton** [gigobyte/purify#121]
```diff
- const just = <T>(value: T): Just<T> => new Just(value)
+ const just = <T>(value: T): Maybe<T> => new Just(value)
```

ref: https://github.com/gigobyte/purify/blob/4de6d71e832aa99d091e783e20cf22b9ef154949/src/Maybe.ts#L452

**Comment by gigobyte** [comment]
It doesn't look intentional, I'll look into it.

**Comment by gigobyte** [comment]
Fixed.

**Comment by imcotton** [comment]
Thanks for the fixing 👏 
At the meantime one could use `Maybe.of` as alternative btw.
