### ISSUE TITLE
[feature] Either#toList()

### ISSUE THREAD

**Issue by imcotton** [gigobyte/purify#123]
Much like `Maybe#toList()`, but always returns fixed array, e.g.:

```typescript
const [ left = 0, right ] = Right(42).toList();
```

```typescript
const [ err, data ] = getEither().toList();

if (err == null) {
    console.info(data);
}
```

How does it looks like?

**Comment by gigobyte** [comment]
Is your suggestion inspired by Go? The second example looks a lot like it.

I don't think that this API would be very useful, I personally prefer the declarative version of the code:
```js
getEither().ifRight(data => console.info(data)).map(data => /* do something with data */)
```

**Comment by imcotton** [comment]
Yes, it's pretty much like Go's error system.

I think in FP context, the Maybe Functor or IO Monad is indeed to get the job done, however sometimes still need way to bridge out, such as `.extract()`:

```typescript
const aboveTen = (n = 0) => n < 10 ? Left(n) : Right(n);

const result = aboveTen(14)
    .mapLeft(n => new Error(`${ n } is less than Ten`))
    .map(n => `good, you're ${ n }!`)
    .extract();

if (result instanceOf Error) {
    console.error(result.message);
} else {
    console.log(result);
}
```
With `.toList()` and destructuring, code would have clean separation from two aspect.

Overall, I think the `Either#toList()` would fits the polymorphous from `Maybe`, which currently missing.

**Comment by gigobyte** [comment]
I have added the `ifLeft` and `ifRight` escape hatches if you need to fire and forget side effects like console.log or setting something in localStorage or whatever. I don't think that the API you're proposing is a good fit for the library, if you still find it useful you can always write a helper function:
```js
const eitherToList = <L, R>(either: Either<L, R>): [L, R] =>
    either.caseOf({
        Left: err => [err, undefined],
        Right: value => [undefined, value]
    }) as [L, R]
```
I have not tested this, but you get the gist.

**Comment by imcotton** [comment]
To clarify, the sample code shown with `console.log` serves demonstration purpose only, real world scenarios where need to interpret with `yield`, early `return`, loop `break` or conjunction with type guards via TypeScript, etc.

I understand your decision, and thanks for the code snippet, will consider using that in the future.
