### ISSUE TITLE
Produce es2018 target as additional aside with es5 to NPM

### ISSUE THREAD

**Issue by imcotton** [gigobyte/purify#126]
Targeting down to `es5` right now is indeed allowing old system to benefit from the module, in additional to that, could be great to have `es2018` without `downlevelIteration` flavor placed so that lots of modern users could opt-in as needed?

I've tested a little bit on local with small changing in build steps, wondering would that be OK to proceed with PR to make the cut?

**Comment by gigobyte** [comment]
Wouldn't removing `downlevelIteration` actually break projects using es5?

**Comment by imcotton** [comment]
Sorry, should have made it more clear, please see below:

```
npm/purify-ts/

├── Either.d.ts
├── Either.js
├── Tuple.d.ts
├── Tuple.js
└── es        <------------- es2018 goes into here
    ├── Either.d.ts
    ├── Either.js
    ├── Tuple.d.ts
    └── Tuple.js
```

**Comment by gigobyte** [comment]
Seems useful, I'll look into it. PRs are also welcome.
