### ISSUE TITLE
Docs contain some typos.

### ISSUE THREAD

**Issue by gjungb** [gigobyte/purify#128]
While sitting on public transport this morning I was informed about your awesome project by a German news site for techies.
Checking out the documentation I stumbled upon some minor typos.
Gonna submit a PR soon...

**Comment by gigobyte** [comment]
Sounds really cool, can you send me a link to that site?

**Comment by gjungb** [comment]
sure enough:
[Purify: Library für funktionales Programmieren in TypeScript](https://entwickler.de/online/javascript/purify-library-579918490.html)

Will close the issue, thx for merging that fast 😃
