### ISSUE TITLE
fantasy-land Filterable

### ISSUE THREAD

**Issue by imcotton** [gigobyte/purify#134]
- Seems `Either#filter` is missing in compare to `Maybe#filter`?
- In addition, would be nice to have `fantasy-land/filter` on both above as well.

ref: https://github.com/fantasyland/fantasy-land#filterable

**Comment by gigobyte** [comment]
Seems like Filterable was added after the initial implementation of Maybe and Either in purify, so that's why it's missing.

Thanks for the heads up!

**Comment by gigobyte** [comment]
The only possible instance for Filterable Either is `(Monoid m) => Filterable (Either m)`, which this library cannot support. But I'll add the fantasy-land method to Maybe.
