### ISSUE TITLE
single entry point for imports?

### ISSUE THREAD

**Issue by cakekindel** [gigobyte/purify#145]
Hi 👋 love this repo. I'm writing this issue more to start a conversation and ask if this style of import structure was considered:

```ts
import { Either, Just, MaybeAsync } from 'purify';
...
```
vs the current pattern of:

```ts
import { Either } from 'purify-ts/Either';
import { Just } from 'purify-ts/Maybe';
import { MaybeAsync } from 'purify-ts/MaybeAsync';
...
```

It feels a little counter to other npm libraries that have homogeneous import structures, but if there's a good reason for the current style i'll shut up

**Comment by gigobyte** [comment]
You can already use the first style, try it out! You have to update to 0.14.1 if you haven't.

The second style is used in the docs because of personal preference.

**Comment by cakekindel** [comment]
that's hilarious, i am so behind the times. Thanks for the speedy reply!
