### ISSUE TITLE
I want to use a chain that would change not only the value but also the type of error

### ISSUE THREAD

**Issue by ParomovEvg** [gigobyte/purify#160]
Now the function chain is useless if I want to return Either in chain, it more likely will have a different type of error
Example
```js
this.phoneService.findPhone(createPhoneDto).chain(phone => {
      return this.passwordService.checkPhonePassword(phone, createPhoneDto);
})
this.phoneService.findPhone() // => EitherAsync<PhoneNotFound, Phone>
this.passwordService.checkPhonePassword() // => EitherAsync<NoPhonePassword, boolean>
```
I would like that would be after the call cahin
`EitherAsync<PhoneNotFound | NoPhonePassword, boolean> `
type
Or tell me how can I do it differently

**Comment by gigobyte** [comment]
This is a known problem in the Haskell world. Unfortunately there is not a simple solution in Haskell since of the stricter type restrictions, but I guess we can experiment in TypeScript, your suggestion seems reasonable, I'll look into it.
