### ISSUE TITLE
isRight() is not type guarding

### ISSUE THREAD

**Issue by moltar** [gigobyte/purify#161]
I can't seem to get this right. Why is `isRight()` not type guarding the `data` object?

Take a look here, please:

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/3489c27d6026b2af7728cd9404fb5066e90210e2/cases/purify-ts.ts#L25

Thanks.

**Comment by gigobyte** [comment]
`isRight` is part of another data type, not Codec. If you want to use the type guarding then you should create an intermediate variable:

```
const decodedData = dataType.decode(data)

if (decodedData.isRight()) {
    return decodedData.extract()
}
```

**Comment by moltar** [comment]
Awesome! Thanks for the quick response. I have fixed it now.
