### ISSUE TITLE
Codec returned from Codec.interface requires field value

### ISSUE THREAD

**Issue by airtoxin** [gigobyte/purify#172]
I want to declare interface with optional field.
So I use[`nullable`](https://gigobyte.github.io/purify/utils/Codec#oneOf) with bit change: add undefinedType

```ts
function nullable<T>(codec: Codec<T>): Codec<T | null | undefined> {
  return oneOf([codec, nullType, undefinedType]);
}
```

then declare interface and object value.

```ts
const MyObject = Codec.interface({ id: string, name: nullable(string) });
type MyObject = GetInterface<typeof MyObject>;

// Property 'name' is missing in type '{ id: string; }' but required in type '{ id: string; name: string | null | undefined; }'.
// const obj1: MyObject = { id: "1" };
const obj2: MyObject = { id: "1", name: undefined };
```

`obj1` causes compile error because field of name must have a value even if type of value is undefined so, I have to declare undefined explicitly 😢

Another problem,
`MyObject` Codec can't decode `obj1` as `MyObject`.

```
// {
//   __value: 'Problem with property "name": it does not exist in received object {"id":"1"}'
// }
console.log(MyObject.decode({ id: "1" }));
```

This behavior is clumsy to use.
(example usecase: api request validation with optional parameter.)

[full example](https://playground.type-puzzle.org?c=H4sIAAAAAAAAA5VTW0%2FbMBT%2BK0d%2BaSuV9LIbCgyNIW3iYWPS%2BjSCkJs46QHH9myHruvy33fskNKi8TBVbe3j4%2B9me8tyXQiWMqyNth62mQK4oFI%2BDiPnLaoqDlUj5WJjRJw0qhAlKlHsKlqJqzKOPgt%2FqbywJc9Fploora4hY6axWG6OvMvYSaYyVTYq96hVBOZLKU4XZ8MgJk87ATQf7YbwJ%2FbR3476rBNrhW%2Bs6viH1xFg%2FCT2UOnNiKjbwJ5r5Tx82Vwt70Tu4X3Hk2AvfLgFLNLePyhei3SndNiVR9AGPE%2FA%2B0j7%2Fk%2FDoi53y2fR%2BmQC36w2wvoNDAL0ANBBjc4RKqCCCDnYl3AC7QCWjSe7Pxu0oniprVPazf4RWsBJooIuAb28m6X76ju0jM0yBu1JHxS1zV9q69PZccR9kWMbfwFubx%2B4bKhnQL4pwBrW6Fdg%2BhAyFiAylgJ6KLRwoLQH8QuJmnxakQt8IGDd0W8zhgV1R%2Fp2EEnaTqqWIpG6GvZSEzpVOtnhga1RODY2Zt7RlhIrlm7pGdQGpbBXJlxKF0pKX9ZGYo7%2BXG1Y6m0jxiwkm%2FuvFOvFSuT37rD%2B6fFSh8v2bOkjquKCS3lujHyG1l%2BGS4UeucTfPGD0PU8yFit8BG3bMSuEERS5yjFQXW9jhvSSdw%2BNHJJBE2qNiqOCSg%2FCuojOpsnsdTJjAcnlFk1HynoPXIYDqiyv63CXnOeq4LYAiUvL7QZKbSH4%2FB73BhjuA9d8Op8eTWdH87eL2XH6ZprO3yXH89kP6pCo7rtoTU2dK%2B%2BNSyeT9XqdUOXOJXQKE8Pze16JyZMPMssbv9I2bu1cVljp5YYIx0zUHGVfEs7PP1ShEsDCVtMsJbqViLsbJ%2BzLCC5BieLh1SEAjZWnLwUXc%2F5%2FjBv6%2FAVFV6LPagUAAA%3D%3D)

**Comment by gigobyte** [comment]
Thank you for your detailed issue!

I have no idea how I missed that, I'll try to get a new release out soon that addresses that.

**Comment by airtoxin** [comment]
Thank you for your quick support!
I'm trying to define new Codec to solve that and it maybe works fine (I don't know what encode should do).

```ts
export const Interface = <
 Required extends Record<string, Codec<any>>,
 Optional extends Record<string, Codec<any>>
>(
 required: Required,
 optional: Optional
): Codec<
 { [K in keyof Required]: GetInterface<Required[K]> } &
   { [K in keyof Optional]?: GetInterface<Optional[K]> }
> =>
 Codec.custom({
   decode: (input) => {
     if (typeof input !== "object" || Array.isArray(input) || input == null)
       return Left(`Input value must be object ${input}`);

     for (const [key, value] of Object.entries(required)) {
       const decoded = value.decode((input as any)[key]);
       if (decoded.isLeft()) return decoded;
     }
     for (const [key, value] of Object.entries(optional)) {
       const inputValue = (input as any)[key];
       if (inputValue == null) continue;
       const decoded = value.decode(inputValue);
       if (decoded.isLeft()) return decoded;
     }
     return Right(input as any);
   },
   encode: (input) => input,
 });
```

Here is a suggestion for changing api.

`Codec.interface(requiredProperties: T, optionalProperties: U = {})`
Newly added second argument is optional, so there are no breaking change.
How is that?

**Comment by gigobyte** [comment]
I've removed the `undefinedType` codec and I've added an `optional` codec combinator. You will still need to explicitly write `undefined` when you create a literal of that type, but that was a design decision that I decided to make to keep the types of the library simple and as understandable as possible (the Codec types are complex enough as it is.)

**Comment by airtoxin** [comment]
Thanks!!
I can't wait new release 😄
