### ISSUE TITLE
Proposition of a method `toEitherAsyncSwap` on maybeAsync

### ISSUE THREAD

**Issue by JeromeBu** [gigobyte/purify#177]
First, thank you first this great library !

When we want to check the existence of something before going on with the program, we can use `MaybeAsync` and then `.toEitherAsync`

I found myself with the opposite case. I want to check that something is not here before going on. Consider the following :

```typescript
type Person = { id: number };

function findPerson(id: number): MaybeAsync<Person>;
function save(person: Person): EitherAsync<Error, Person>;

const create = (person: Person): EitherAsync<Error, Person> => {
  const maybeAsyncPerson = findPerson(person.id);

  return maybeAsyncPerson
    .toEitherAsyncSwaped(new Error("Cannot create Person which already exists"))
    .chain(() => save(person));
};
```

I would be happy to make a PR with this new method `toEitherAsyncSwaped` if you find it interesting.

We can also imagine a `swap` on `eitherAsync`, which would be more generic. Then the previous case would become :

```typescript
const create = (person: Person): EitherAsync<Error, Person> => {
  const maybeAsyncPerson = findPerson(person.id);

  return maybeAsyncPerson
    .toEitherAsync(new Error("Cannot create Person which already exists"))
    .swap()
    .chain(() => save(person));
}
```

Maybe there is a different way that I did not think of...

**Comment by gigobyte** [comment]
Thank you for proposal!

It's funny that a couple of days ago I looked at `swap` and a couple of other Either methods and I thought: "I won't add them for now, probably no one will use them". Well thanks for proving me wrong 😄 

I would definitely prefer adding a `swap` method instead of your first suggestion. Until then, as always there is an ugly workaround:

```typescript
const create = (person: Person): EitherAsync<Error, Person> => {
  const maybeAsyncPerson = findPerson(person.id);

  return maybeAsyncPerson
    .toEitherAsync(null)
    // if there is a person turn the either into a left
    .chain(_=> liftEither(Left(new Error("Cannot create Person which already exists")))
    // chainLeft will now run either with a null or with an error, depending on the line above
    .chainLeft(err => err === null ? save(person) : liftEither(Left(err))
};
```
