### ISSUE TITLE
Make more methods generic in their argument

### ISSUE THREAD

**Issue by libre-man** [gigobyte/purify#179]
It would be nice if some methods would be generic on the argument type. For example currently `Maybe<T>::alt` takes and returns a `Maybe<T>`. This makes it impossible to do something like `just(5).alt(just('different type'))`. It would be nice if `alt` accepted a `Maybe<U>` and returned a `Maybe<T | U>` (or even `this extends AlwaysJust ? Maybe<T> : Maybe<T | U>`). I think this change can be made without breaking backwards compatibility, as `T | T` is equal to `T`.

**Comment by gigobyte** [comment]
I have also been thinking about this. I am not convinced that it would be better to turn everything into an union for the following reasons:

* It would report the error later, which would result in a worse DX. Consider the following snippets, in the case of a long chain it would highlight the whole body of the function and since most codebases use complex types the errors would get pretty ugly:
```typescript
const foo = (): Maybe<number> => Just(5).alt(Just('bar'))
//                                           ~~~~~~~~~~~
// Argument of type 'Maybe<string>' is not assignable to parameter of type 'Maybe<number>'.
//   Type 'string' is not assignable to type 'number'.
```
```typescript
const foo = (): Maybe<number> => Just(5).alt(Just('bar'))
//                               ~~~~~~~~~~~~~~~~~~~~~~~~
// Type 'Maybe<string | number>' is not assignable to type 'Maybe<number>'.
//   Type 'string | number' is not assignable to type 'number'.
//     Type 'string' is not assignable to type 'number'.
```
* You can already manually add the type parameter with the union type wherever you need it
```typescript
const foo = () => {
  const bar: Maybe<string | number> = Just(5)

  return bar.alt(Just('Foo'))
}
```

**Comment by libre-man** [comment]
I understand where you are coming from, but I'm not entirely convinced that using a local variable with a type annotation is always the way to go. First this is only really possible by also importing the type returned in this file, not really a problem, a bit annoying though. Second it means that I sometimes have to create a new local variable just for type annotation, if I want to more with the one `Maybe<T>` then just doing an `alt` (or another operation) on it.

I'm not entirely sure that the DX is actually worse when it is a union type, in the first example I would argue that the function is returning something different than indicating, not that the argument to `alt` is incorrect. And anyway in the second case for the first example I would know how to solve it if it is a bug (fix the argument to `alt`), especially when inspecting the type of `alt`. However, currently if it is intended behavior the solution isn't indicated at all by the compiler, and I'm afraid many people would simply cast away the error (by doing `Just(5) as Maybe<string | number`, which loses almost all type information).

Again I understand where you are coming from, and as it's your library and the issue isn't that large or breaking it is no big deal if you don't want to change the design. Another possibility would be to add a second class of methods with this behavior, but I don't really think that is a direction worth taking as it would clutter up the code even more.

**Comment by gigobyte** [comment]
Don't worry, I appreciate your feedback :smile:. I will leave this issue open for now, I can see some value in your suggestion so I'm open to other people sharing their experience.
