### ISSUE TITLE
Another combinator for monad transformer composition

### ISSUE THREAD

**Issue by poslegm** [gigobyte/purify#180]
Hello!

There is a common use case when you need to compose `EitherAsync` with synchronous `Either` function:

```typescript
function validate(doc: Document): Either<Error, ValidatedDocument> {
  // ...
}

function fetchDocument(id: string): EitherAsync<Error, Document> {
  // ...
}

fetchDocument("123").chain(doc => liftEither(validate(doc)))
```

It would be nice to have combinator which will lift `Either` itself. [cats](https://github.com/typelevel/cats) library has [subflatMap](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/EitherT.scala#L396-L397) method for this purpose.

Possible API:

```typescript
subchain<R2>(f: (value: R) => Either<L, R2>): EitherAsync<L, R2>

// ========

fetchDocument("123").subchain(doc => validate(doc))
```

What do you think?

**Comment by gigobyte** [comment]
I dig it,
```typescript
fetchDocument("123").subchain(validate)
```
does indeed look nicer than
```typescript
fetchDocument("123").chain(doc => liftEither(validate(doc)))
```

Kinda shameful that the only documentation for subflatMap is the source code itself, but then again this is a common problem among FP libraries. I'm trying to figure out where the "sub" part came from and if we can find a better name for this.

**Comment by poslegm** [comment]
> the only documentation for subflatMap is the source code itself, but then again this is a common problem among FP libraries

The sad truth

> I'm trying to figure out where the "sub" part came from and if we can find a better name for this.

I didn't find the sources of this naming in the commit history. I guess that `sub-` because in `Promise<Either<A,B>>` `Either` is an inner part of entire datatype (subset maybe).

**Comment by gigobyte** [comment]
I like how succinct `subchain` is, but I'm wondering if something more obvious like `liftThenChain` or `chainEither` is not a better name.

**Comment by poslegm** [comment]
`chainEither` looks simple and clean 👍

**Comment by paduc** [comment]
Funny, I was just discussing the need for this to a friend of mine yesterday.

Now I'm wondering if the same cannot be done for these cases
```
fetchDocument("123").chain(doc => liftPromise(promiseFn(doc)));
fetchDocument("123").chain(doc => fromPromise(eitherPromiseFn(doc)));
```

**Comment by gigobyte** [comment]
If we have a method for each type you can lift it will create a combinatorial explosion:
`chainEither`
`chainEitherLeft`
`chainPromise`
`chainPromiseLeft`
etc

**Comment by paduc** [comment]
I see your point, even though I'm not sure it would be that bad to have many methods.

How about have a single `.chain(fn)` method that detects the return type of the given function ?

**Comment by gigobyte** [comment]
That's technically possible and even that's how `Promise.then` works, but I really dislike this design. I prefer things to be explicit.

**Comment by paduc** [comment]
I thought so.

I'm thinking about maintainability for developers that aren't familiar with monads and even less so with purify. If i'm having a hard time reading code that contains `liftEither/liftPromise/fromPromise/...`, I'm afraid they will make future maintainers miserable. I need something that is very readable.

Maybe purify is not the tool for my specific needs. Or maybe I can find a way to abstract some of this complexity away.

**Comment by gigobyte** [comment]
I agree that EitherAsync is a bit on the heavy side when it comes to jargon. I'll try to think of something that solves your usecases, as I said I like how `subchain`/`chainEither` looks but I don't like how it creates too much ways to do the same thing.

**Comment by paduc** [comment]
Thanks @gigobyte !

I agree we're talking about syntactic sugar here (ie. adding yet another way to do the same thing).

**Comment by gigobyte** [comment]
Now that `chain` supports PromiseLike (in master, it's not released yet), this leaves out only chaining `Either<L, R>` and `Promise<R>`.
```typescript
fetchDocument("123").chain(doc => fromPromise(eitherPromiseFn(doc)));
```
will become just
```typescript
fetchDocument("123").chain(doc => eitherPromiseFn(doc));
```
This makes me wonder if I should just add `chainEither` and `chainPromise` to address all usecases or I should hold back on expanding the API too much.

**Comment by chenguo** [comment]
You wouldn't `.chain` a `Promise<R>`, right? You would `.map` a `Promise<R>`?

For `EitherAsync.chainEither`: this is a deviation from the baseline `interface Either<L,R>`, now that EitherAsync has to have special handling for the baseline Either. From an end user perspective it would be useful to have the same interface for Either and EitherAsync, so if anything it should be `chain((v: R) => Either<L, R>) ` and `chainAsync((v: R) => Promise<Either<L, R>>)`, as opposed to `chain((v: R) => Promise<Either<L, R>>)` and `chainEither((v: R) => Either<L, R>)`

I also wouldn't mind if EitherAsync just always lifted plain Eithers into a Promise. I think libraries like Bluebird what mainly deals in promises do this, just because it's simpler to always reason in terms of just asyncs, rather than in both async and sync code.

**Comment by gigobyte** [comment]
@chenguo The `chain` name is a monadic bind and has specific semantics, it will always mean
```haskell
m a -> (  a -> m b) -> m b
```
where `m` is the data type you're working with. With that in mind, `chain` in EitherAsync working with plain Eithers is just wrong and "have the same interface as Either" is not a good reason to break that rule.

**Comment by gigobyte** [comment]
> You would .map a Promise<R>?

You raise a good point, but if a Promise fails the EitherAsync will be a Left, so it fits `chain`. You can't have a `map` changing the constructor (`Right -> Left`).

**Comment by chenguo** [comment]
Any further thoughts on this? I'm trying to switch back to Purify master from a custom deployment I had, where I added some syntactic sugar around async handling, and having to go from something succinct like `someAsyncEither.chain(myfunc)` to `someAsyncEither.chain(foo => EitherAsync.liftEither(myfunc(foo))` in dozens of places is kinda painful.

IMO it dramatically reduces readability, esp for engineers who are less familiar with these semantics. We mostly even tuck Promises behind awaits, so for some of the people I work with this is a radical shift, and it would be really helpful to be able to reduce indirection and mental tracking of things where possible.

I know you're busy, if you have a general direction / vision, I'd be happy to help out with the legwork.

**Comment by chenguo** [comment]
It looks like the `PromiseLike` interface we added recently actually obviates the need for `liftEither`, so in my above example of: `someAsyncEither.chain(myfunc)`, I don't need to go the full `liftEither` route, I can actually do something like `someAsyncEither.chain(async (foo) => myfunc(foo))`

(myfunc returns an either, I should've made that clear in my previous message)

That's not too bad, I think we can work with that, so I'm gonna turn down the urgency of my plea a bit :) But speaking towards the longer term, I do think it would be helpful for Purify to have some more syntactic sugar around mixing async / sync code.

**Comment by gigobyte** [comment]
> someAsyncEither.chain(async (foo) => myfunc(foo))

That's really clever, I like it.

EitherAsync started as a copy of `EitherT IO` from Haskell but it's becoming more and more like a Promise that works with Either. I guess I don't mind that much, I'll give more thought about your suggestions.

**Comment by gigobyte** [comment]
Here's all possible type combinations and how you can work with them seamlessly:
```typescript
// Type: T -> U
someEitherAsync.map(x => x + 1)
```
```typescript
// Type: T -> Either<string, U>
someEitherAsync.chain(async x => func(x))
someEitherAsync.chain(x => EitherAsync.liftEither(func(x)))
```
```typescript
// Type: T => Promise<U>
someEitherAsync.chain(x => EitherAsync.liftPromise(func(x))
```
```typescript
// Type: T => Promise<Either<string, U>>
someEitherAsync.chain(x => func(x))
```
Only one of those require using a helper function so I think that the API is good enough for these usecases.
