### ISSUE TITLE
Question - Codec decoding with multiple errors

### ISSUE THREAD

**Issue by sdn90** [gigobyte/purify#186]
Hi,

Thanks for your work on this library! I'm really enjoying using it.

Is there a way to get multiple errors from a decode result?

Example
```typescript
// codec
const BlogPostCodec = Codec.interface({
  name: string,
  authorId: number
});
```

I'm trying to build an object like this:
```typescript
{
  name: "must be a string",
  authorId: "must be a number"
}
```

**Comment by gigobyte** [comment]
Hello,

This is not possible currently. The implementation of `Codec.interface` is 35 lines long though, so you can create your own version of it that doesn't immediately return on an error, but accumulates the errors in an object. [Here](https://github.com/gigobyte/purify/blob/master/src/Codec.ts#L99) is the source.
