### ISSUE TITLE
This package specifies a 'main' module field that could not be resolved

### ISSUE THREAD

**Issue by ACHP** [gigobyte/purify#195]
Hi,
I did install this package in a react-native project and I got this error.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/9294168/84196707-e4e62a00-aaa0-11ea-9bad-51675f5994a6.png">

The error comes from the package.json declaring the `main` module to be `lib/main.js` but no `lib` folder exist.
(there is also a `types` props pointing to `lib/index.d.ts`)

This seems to be caused by the [publish.ps1](https://github.com/gigobyte/purify/blob/master/publish.ps1) file that copy the package.json inside the lib folder itself before publishing it.

Also : Thank you for this great lib :)

**Comment by gigobyte** [comment]
Interesting, seems to only happen in react-native projects. Thanks for the notice, I'll fix it when I have some time available 😄.

By the way, can you import via `import { Maybe } from 'purify-ts/Maybe`?
