### ISSUE TITLE
Fantasy Land implementation list

### ISSUE THREAD

**Issue by darky** [gigobyte/purify#196]
> Purify is a library for functional programming in TypeScript. Its purpose is to allow developers to use popular patterns and abstractions that are available in most functional languages. It is also Fantasy Land conformant.

Maybe need to place it here? 
https://github.com/fantasyland/fantasy-land/blob/master/implementations.md

I try to find library like this in *Fantasy Land implementation list* and was surprised, when find it from other sources.

**Comment by gigobyte** [comment]
I've made a PR to fantasy-land :)
