### ISSUE TITLE
Support basic function composition

### ISSUE THREAD

**Issue by mperktold** [gigobyte/purify#199]
I cannot find any function composition operators such as `f . g` in Haskell, or [`flow`](https://github.com/gcanti/fp-ts/blob/master/docs/modules/function.ts.md#flow) and [`pipe`](https://github.com/gcanti/fp-ts/blob/master/docs/modules/function.ts.md#pipe) in fp-ts.

I think these would be a great fit for this library as they represent a simple and fundamental concept of fp.

**Comment by gigobyte** [comment]
I think I'll wait for https://github.com/microsoft/TypeScript/pull/39094 to be merged and TS 4.0 to be released before adding such functions.

**Comment by pyrho** [comment]
TS4 is now available via `npm i typescript@beta` ! 
See the [announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/) :)

**Comment by pyrho** [comment]
@mperktold In the meantime, you can use the following using Ramda's [pipe](https://ramdajs.com/docs/#pipe) function (or [compose](https://ramdajs.com/docs/#compose)) as the following snippet demonstrates:

```typescript
import { Maybe } from 'purify-ts/Maybe';
import * as R from 'ramda';

const maybeMap = (fn: (a: number) => number) => (x: Maybe<number>) =>
    x.map(fn);

const pipeline = R.pipe(maybeMap(R.inc), maybeMap(R.inc));

pipeline(Maybe.of(1));
// => Just(3)
```

**Comment by gigobyte** [comment]
So I got confused here, I was thinking about `curry`, but the request was for a `compose/flow/pipe` type of function, which I won't add in this library until TypeScript starts propagating generics and the function becomes type-safe.

I did get something out of this issue though, I spent a lot of time implementing a properly typed `curry` which will be available in the next version, so there's that.

**Comment by mperktold** [comment]
> So I got confused here, I was thinking about curry, but the request was for a compose/flow/pipe type of function, which I won't add in this library until TypeScript starts propagating generics and the function becomes type-safe.

To be honest, I don't know what you mean here.
The following works nicely [as of TypeScript 3.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#higher-order-type-inference-from-generic-functions).

```ts
function compose<T, U, V>(f: (x: T) => U, g: (y: U) => V): (x: T) => V {
  return x => g(f(x));
}

interface Box<T> {
  value: T;
}

function makeArray<T>(x: T): T[] {
  return [x];
}

function makeBox<U>(value: U): Box<U> {
  return { value };
}

// type inferred as `<T>(x: T) => Box<T[]>`
const makeBoxedArray = compose(makeArray, makeBox);

makeBoxedArray("hello!").value[0].toUpperCase();
```

[Playground Link](https://www.typescriptlang.org/play?ts=3.5.1#code/GYVwdgxgLglg9mABBOBbADnAzgUwDwAqANIgKokBqAfABTABciNAHowQJSIC8VZJA5oxoBPRqU49EFdkNaIO3XhUQBvAFCJEAJxxQQWpM0WJ+dFu3YBuNQF81amGCg4twAIYQciAEJxmhXnVNADc3ABsQHDZrOzVQSFgERFQ3AGscAEEtLTdhAJY2GXkAbQBdVQ1tXX0kYuZSmPt46HgkFPTff1JaUIiosiLOvG6KzR09A1VEXsjEG0a1AHpFxChhdC9HYBcdABNENyxEAAN8uQVJIYIyqmO1FDAsKGS0nE6cXayc4W5kNExcDR2plsrkSMDOlZ7BC-B8vrkaAAiAAWODCYTgAEJEewAHQzHDFAAMpVxUDgpHQGy0AGFDjgaFCgA)

Are there still some situations where the generics are lost?

> I did get something out of this issue though, I spent a lot of time implementing a properly typed curry which will be available in the next version, so there's that.

That's great to here!
To be clear, I suggested these additions because I think they would make sense, not that I would desperately need them.
It's perfectly fine if you disagree.

**Comment by gigobyte** [comment]
That is really interesting! I remember now that they fixed that behavior some time ago, but I tested the ramda compose and it turned the generic into `unknown`, guess they haven't fixed their compose types. Your implementation works great, I'll use it, thanks!

**Comment by mperktold** [comment]
Awesome! 👍 
I just copied it from the linked Handbook page. 😄

**Comment by stellarbear** [comment]
Any updates for ts-purify regarding pipe & compose?
