### ISSUE TITLE
Add DSL for defining ordering functions

### ISSUE THREAD

**Issue by mperktold** [gigobyte/purify#200]
It would be nice to have a declarative DSL for defining order functions as being expected by `List.sort` or `Array.prototype.sort`.

I am thinking of something similar to the API provided by [`java.util.Comparator`](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/Comparator.html), or extensions thereof in other JVM languages like [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.comparisons/) or [Scala](https://www.scala-lang.org/api/current/scala/math/Ordering.html).

It doesn't matter whether the DSL consists of chainable methods of some `Ordering` prototype, or just higher order functions.

So to sort an array of people:

```ts
const orderedPersons = List.sort(comparePersons, persons);
```

instead of writing

```ts
function comparePersons(p1: Person, p2: Person): Order {
  const byLastName = compare(p1.lastName, p2.lastName);
  if (byLastName !== Order.EQ)
    return byLastName;
  const byFirstName = compare(p1.firstName, p2.firstName);
  if (byFirstName !== Order.EQ)
    return byFirstName;
  return compareByDay(p1.birthdate, p2.birthdate);
}
```

I wish I could write something like

```ts
const comparePerson = Comparing.by(p => p.lastName)
                              .thenBy(p => p.firstName)
                              .thenBy(p => p.birthdate, compareByDay)
                              .asFunction()
```

or alternatively something like

```ts
const comparePerson = comparingSequentially(
  comparingBy(p => p.lastName),
  comparingBy(p => p.firstName),
  comparingBy(p => p.birthdate, compareByDay)
);
```

As a bonus, it would be nice if one could convert functions returning `Order` to functions returning `number` and vice-versa, for being able to define them once and use them for both `List.sort` and `Array.prototype.sort` in a convenient way, such as:

```ts
persons.sort(orderToNumber(comparePerson));
```

Alternatively, you could directly use numbers as the values of the `Order` enum, but then you would [lose the strong typing benefits](https://github.com/microsoft/TypeScript/issues/32690).

**Comment by gigobyte** [comment]
That's definitely an interesting suggestion, thanks!

**Comment by gigobyte** [comment]
While this looks like an useful utility, I don't see the connection with FP. At least I couldn't find any approaches to sorting in functional languages that are any different than traditional languages.

I'll be closing this thread for this reason, if anyone has interesting insight into this sort of API - please share them, preferably in a new issue.
