### ISSUE TITLE
oneOf makes the assumption that the encoded value is decodable

### ISSUE THREAD

**Issue by ccapndave** [gigobyte/purify#204]
The implementation of `oneOf` decides which encoder to use based on the first *decoder* that can handle the input.  However, if the codec does any kind of transformation, this is going to fail.

Here is a real-world example.  I am using https://easymoney.now.sh/ to manage amounts of money in my application.  These need to be sent over the wire, so I use a `Codec` to convert from a plain representation to an `easymoney` object (using their `createMoney` method).

```ts
const moneyCodec = Codec.custom<MoneyBase<string>>({
  decode: payload =>
    Codec.interface({
      amount: number,
      currency: string
    })
      .decode(payload)
      .map(({ amount, currency }) => createMoney({ amount, currency })),
  encode: value => ({ amount: parseInt(value.getAmount()), currency: value.getCurrency() 
});
```

This means, for example, I can encode an amount of money on the server, send it to the client, and then it can decode it and end up with the same `easymoney` object.

Now imagine that I have a type like this:

```ts
type CheckoutPrice =
  | { tag: "no_discount"; price: MoneyBase<string> }
  | { tag: "discounted"; price: MoneyBase<string>, discount: MoneyBase<string> };
```

I assume that the way to write the `Codec` is:

```ts
const checkoutPriceCodec: Codec<CheckoutPrice> = oneOf([
  Codec.interface({
    tag: exactly('no_discount'),
    price: moneyCodec
  }),
  Codec.interface({
    tag: exactly('discounted'),
    price: moneyCodec,
    discount: moneyCodec
  })
]);
```

This will work perfectly for decoding, but for encoding it will fail to run `moneyCodec.encode` against `price` (and `discount` in the second type constructor).

This is because the implementation of `oneOf` decides which encoder to use based on which decoder can decode it (https://github.com/gigobyte/purify/blob/master/src/Codec.ts#L307-L312).

In this case, the prices are `easymoney` objects and so no decoder will be able to handle them, no encoder will be chosen, and the fields will be returned unchanged.

I'm not quite certain what would be the most elegant solution for this.  I vaguely feel that `oneOf` could support an extra parameter or some extra info attached to each case such that it can use that to select an encoder.   For example, in this case (and probably all cases of coding discriminated unions) we would want to choose based solely on the `tag`.

**Comment by ccapndave** [comment]
Perhaps a nice api might be to have a tuple with the discriminator/matcher codec first, and then the rest of it:

```ts
const checkoutPriceCodec: Codec<CheckoutPrice> = oneOf([
  [ Codec.interface({ tag: exactly('no_discount') }), Codec.interface({ price: moneyCodec })],
  [ Codec.interface({ tag: exactly('discounted') }), Codec.interface({
    price: moneyCodec,
    discount: moneyCodec
  })
]);
```

Internally `oneOf` could use the new `intersect` function to put these together into a single decoder and encoder, but use only the first element of the tuple for deciding which encoder to use.

**Comment by ccapndave** [comment]
I've implemented a function `matchedOneOf` that implements the idea above (but using an object instead of a tuple) in https://github.com/ccapndave/purify/tree/matchedOneOf.

If you think this is a good API, it would probably be good to integrate it into the original `oneOf` function, but allow it to take either an array of codecs, or an array of `{matcher, codec}`.

Thanks to @medfreeman for his help with the types!

**Comment by gigobyte** [comment]
I gave this a lot of thought, I was trying to figure out a way to handle this without changing the API and I believe this should work:
```typescript
for (const codec of codecs) {
  const res = codec.decode(codec.encode(input))
  if (res.isRight()) {
    return codec.encode(input)
  }
}
```
Basically, encode the input before trying to decode it. This will only break if `encode(decode(x)) != x` which is a bad codec to begin with and this detail can be added to the documentation. What do you think?

**Comment by ccapndave** [comment]
That's very clever :)  Did you try it on the test?

**Comment by gigobyte** [comment]
Yeah, seems to work.
