### ISSUE TITLE
Add a function that checks if a value is a `Maybe`

### ISSUE THREAD

**Issue by libre-man** [gigobyte/purify#216]
When porting over legacy code (i.e. non typed) it is sometimes useful to check if a specific value is a `Maybe`. An example for this would be to wrap a value in `Maybe` if it is not already a maybe. Would it maybe be possible to add a `Maybe::isMaybe` method that checks if the given argument is a `Maybe`?

**Comment by gigobyte** [comment]
In untyped code you can do:
```javascript
Just(5).constructor === Maybe // true
```
Does that solve your case?

**Comment by libre-man** [comment]
I'm using something like that in our code, but I think that having it as a static function on `Maybe` would be nice. Especially as I'm not sure if it is guaranteed that the constructor of `Just` and `Nothing` will be `Maybe` in the future.

**Comment by gigobyte** [comment]
Sure, I don't mind adding it. By the way, the `constructor` is guaranteed otherwise purify becomes fantasy-land uncompliant.

**Comment by KevinMGranger** [comment]
One advantage of this approach is that it can act as a type guard.

Plain constructor checking won't act as a type guard:
```typescript
function runEitherAsync(something: unknown) {
    if ((something as { constructor: any }).constructor === EitherAsync) {
        something.run(); // typescript will complain here
    }
}
```

But if pulled out into a separate function:
```typescript
function isEitherAsync(something: unknown): something is EitherAsync<unknown, unknown> {
    return (something as { constructor: any }).constructor === EitherAsync;
}

function runEitherAsync(something: unknown) {
    if (isEitherAsync(something)) {
        something.run(); // all good!
    }
}
```

(Using EitherAsync instead of Maybe because that's the use case I just ran into)
