### ISSUE TITLE
Add property to access definition object of Codec.interface 

### ISSUE THREAD

**Issue by airtoxin** [gigobyte/purify#227]
I want to access internal definition object of `Codec.interface`.

```typescript
const Person = Codec.interface({
  name: string,
  work: Codec.interface({
    company: string,
    address: string
  })
});
```

There are no way to enumerate properties of `Person` programmatically: `name`, `work` and property of work, `company` and `address`.

here's my suggestion.

```typescript
const PersonDef = Person.def // { name: string, work: Codec.interface({...}) }
const WorkDef = PersonDef.work.def // { company: string, address: string }
```

This feature is needed to define new runtime Codec based on existing one.

**Comment by gigobyte** [comment]
Can you expand a bit more about `define new runtime Codec based on existing one`? I'm interested about your usecase.

**Comment by airtoxin** [comment]
Thanks, one of my use case is to change properties to optional.
Next example shows defining request body of updation api from domain model Codec.

```typescript
const PersonUpdateRequestBody = Codec.interface(Object.entries(Person.def).reduce((o, [k, v]) => ({ ...o, [k]: optional(v) }), {}));
```

Another use case is to add some properties to base codec. This can realize diff based model definition.
Next example shows defining detailed-model from summarized-model.

```typescript
const PersonDetail = Codec.interface({
  ...Person.def,
  age: number,
  country: string,
  address: string,
  /* etc */
});
```

**Comment by gigobyte** [comment]
For the second use case, you can use `intersect` from `0.16`:
```typescript
const PersonDetail = intersect(Person, Codec.interface({
  age: number,
  country: string,
  address: string,
  /* etc */
});
```
Since every codec will have a `def`, what would the value be for simple codecs like `string`, `number` etc? I think they'll need to reference themselves. Same for the results of `oneOf`, `exactly` and the like.

**Comment by airtoxin** [comment]
yes, `intersect` resolves second one. It covers almost use case, but first one still needed.
It correspond to mapped types of TypeScript.

I think, `def` is used to type conversion, so it needs only Complex codecs https://gigobyte.github.io/purify/utils/Codec/#oneOf
Complex codecs are accept `Codec<T>`. `def` can change it to `Codec<U>`.

**Comment by gigobyte** [comment]
There is a single `Codec` type though, so you can't separate between complex and simple codecs. If you make the `def` an optional property or something like that, that means that the abstraction is leaky and that the design needs to be better.

To reiterate, it shouldn't be possible to differentiate a codec made with `Codec.interface` from any other codec, a codec is a black box.

**Comment by gigobyte** [comment]
Closing to clear up the backlog, if you have strong feelings regarding this proposal - feel free to comment even though it's closed.
