### ISSUE TITLE
Using purify with Promises

### ISSUE THREAD

**Issue by MarcCoquand** [gigobyte/purify#23]
Hi! Thanks for this fantastic library, it's really helpful and the API is very easy to work with. I was wondering if there are any plans to be able to wrap promises in the api?

**Comment by Vizvoxer** [comment]
@MarcCoquand, I guess, a functional library for async things sounds like FRP libraries (e.g. rxjs, bacon etc.).
But I am curious, what use cases might be for wrapping promises in the pure API?

**Comment by gigobyte** [comment]
I was thinking about implementing a thin wrapper around the Promise API, but I found some libraries that are already FP-friendly that do the same thing like [Fluture](https://github.com/fluture-js/Fluture). I am not sure if it's worth it to duplicate the effort.

**Comment by gigobyte** [comment]
Can you provide me with some example snippets of code that would be better if there was a way to wrap Promises with pure?

**Comment by adrice727** [comment]
@Vizvoxer Are you looking for something `IO` or `Task` to make futures lazy?
