### ISSUE TITLE
Change Left and Right type on chain

### ISSUE THREAD

**Issue by nythrox** [gigobyte/purify#231]
Hi, I was wondering if it's possible to change the type of Left in an Either by using chain, I'm new to FP so I'm not sure if this is intended or if the error I'm getting could possibly be a bug 
```typescript

  const getAnimal = () => Right("Cow");

  const validateAnimal = (animal: string): Either<Error, string> =>
    animal === "cow"
      ? Left(new Error("Animal cannot be a cow"))
      : Right(animal);

  const result = getAnimal().chain(validateAnimal); // Error: Either<Error, string> is not assignable to type Either<never, string>

```

```typescript
  const number = Right("0");    
  number.chain((e) => Left("Sorry, but 0 is not a number!")) // Error: Either<string, never> is not assignable to type Either<never, never>
```

A more realistic example: 

```typescript
   const profile: EitherAsync<string, User> = getProfile()
   const validateRequest : (user: User) => EitherAsync<Error, User> = ...
   return profile
    .chain((e) => validateRequest) // Error:  EitherAsync<Error, User> is not assignable to type EitherAsync<string, User>

```

I get that .chain only lets you change the type of Right, and .chainLeft only lets you change the type of Left, but is this behaviour correct? Or should I be able to change both Left and Right like if it was a map

**Comment by pyrho** [comment]
The [documentation](https://gigobyte.github.io/purify/adts/Either#Left) states that you must provide a type annotation when using Left/Right constructors, otherwise the "other" type will always be `never`.

Try changing: `const getAnimal = () => Right("Cow");` to `const getAnimal = () => Right<String, Error>("Cow");`

**Comment by nythrox** [comment]
Hi, thanks for the quick reply! 
I understand that you can type the constructor to Either<L, R>, but if I wanted to chain it to another Either<L2, R2>, the chain operator would not allow me to do this, since it only allows Either<L,R> (chain) Either<L, R2>.

```typescript

  const getAnimal = () => Right<string, string>("Cow");
  const validateAnimal : (animal: string) =>  Either<Error, string> = ...

  const result = getAnimal().chain(validateAnimal); // Error: Either<Error, string> is not assignable to type Either<string, string>

```

Ideally, I would be able to transform Either<string, number> to Either<Error, string> (changing both types) using chain()

Is the current behaviour intended? Is there a different function I can use for this? If not I can make a pull request adding the extra type, I believe that the functionality already happens under the hood although the type doesn't represent it

**Comment by pyrho** [comment]
After reading the .d.ts it seems you're right I misinterpreted you initial question sorry. I will let someone more competent chime in (:

**Comment by gigobyte** [comment]
@nythrox The 1st and 2nd examples are not related to the 3rd one, @pyrho already helped with that one.

The behaviour is intended. Consider the following example:
```typescript
  const validateAnimal = (animal: string): Either<Error, string> =>
    animal === "cow"
      ? Left(new Error("Animal cannot be a cow"))
      : Right(animal);

const animal: Either<string, string> = Left('something')

const validatedAnimal: Either<Error, string> = animal.chain(validateAnimal)

// This compiles, but the value of `validatedAnimal` is a string, not an Error, since `validateAnimal` never ran
validatedAnimal.ifLeft(err => console.log(err.message)
// expected the Error message, but will log undefined
```

**Comment by nythrox** [comment]
Oh ok, I understand now. Thanks for the explanation @gigobyte @pyrho
