### ISSUE TITLE
.fold(onJust, onNothing) method for Maybe

### ISSUE THREAD

**Issue by val-o** [gigobyte/purify#242]
Hi, enjoying your library, but I was a bit surprised I didn't found .fold method on Maybe type, I suppose I can achieve this by using .caseOf, but it looks a bit more verbose:
This:
```
  const errorText = Maybe.fromNullable(
    ERROR_TRANS_MAP[errors[EField.Name]
  ).fold(t, constUndefined);
```
Instead of:
```
  const errorText = Maybe.fromNullable(
    ERROR_TRANS_MAP[errors[EField.Name]
  ).caseOf({ Just: t, Nothing: constUndefined });

  const errorText = Maybe.fromNullable(
    ERROR_TRANS_MAP[errors[EField.Name]
  ).map(t).extract();
```
I think the same can be applied to Either

**Comment by gigobyte** [comment]
You are right, I decided on implementing `caseOf` as a replacement because it's more explicit.

Incidentally, there is [Either#either](https://gigobyte.github.io/purify/adts/Either#either), which is what you're describing, but I wouldn't recommend using as it might get removed in the future (I don't like having multiple ways to do things)

**Comment by val-o** [comment]
Ah, I see your point. Would it be possible to expose classes somehow so I could augment their prototype with .fold for my project?

**Comment by gigobyte** [comment]
You can already do that, although it's a bit hacky:
```javascript
import { Just, Nothing } from 'purify-ts'

function fold() { ... }

const justPrototype = Object.getPrototypeOf(Just(null))
const nothingPrototype = Object.getPrototypeOf(Nothing)

justPrototype.fold = fold
nothingPrototype.fold = fold
```

I haven't written declaration files in a really long time, but you'll also have to add something similar to your `index.d.ts`:
```typescript
declare module 'purify-ts' {
  interface Maybe {
    fold(...): ...
  }
}

```

**Comment by val-o** [comment]
Indeed, thanks!

**Comment by KevinMGranger** [comment]
I know you don't like multiple ways to do things, but you could compromise with an overload, no?


```typescript
function fold<T, U>(justHandler: (T) => U, nothingHandler: () => U): U;
function fold<T, U>(handlers: {Just: (T) => U, Nothing: () => U}): U;
function fold<T, U>(objectOrJustHandler: unknown, nothingHandler?: () => U): U {
  if (nothingHandler !== undefined && typeof objectOrJustHandler === "function") {
    // two-function-argument case
  else if (nothingHandler === undefined && typeof objectOrJustHandler === "object") {
    // object case 
  } else {
    // error for undefined behavior, although with proper overloads it shouldn't get here
  }
}
```

**Comment by gigobyte** [comment]
That is the same and it's even worse because of the complicated type signature. The only place where I would use overloads in this library is for curried functions.
