### ISSUE TITLE
Widening error values on chaining and similar operations

### ISSUE THREAD

**Issue by bsander** [gigobyte/purify#251]
I have seen this topic come up before in issues on this repo, but I'm not clear on what the problem is so I'm giving it another shot 🙂 

When chaining an either, it would be a huge convenience if the resulting Either would represent the error types of all Eithers involved. Could the signature for this method be changed to:

```
interface Either<L, R> {
  ...
  /** Transforms `this` with a function that returns an `Either`. Useful for chaining many computations that may fail */
  chain<L2, R2>(f: (value: R) => Either<L2, R2>): Either<L | L2, R2>;
}
```

As long as the error can be of both kinds, no type information is lost. If the errors are the same, the type `T | T` would just resolve to `T` so there's minimal added noise. Of course this could be addressed by explicitly widening the error type at the start of the chain, but that requires knowledge of all the errors that may come up, and causes type noise that's not necessary if we let TS infer the error types over the course of the whole chain.

There are also other functions that could benefit from this. fp-ts currently has a `*W` family of functions (like [`chainW`](https://gcanti.github.io/fp-ts/modules/Either.ts.html#chainw)) that does this and it works very well. I would even argue this should be a default, but just being able to opt-in to this functionality would be a big win!

I'm willing to work on a PR for this, but would like to get buy-in for the idea first since a few related issues are closed already (https://github.com/gigobyte/purify/issues/231, https://github.com/gigobyte/purify/issues/160)

**Comment by gigobyte** [comment]
There have been a lot of requests for this. I guess this library's core value, "Emphasis on practical code", is why this library is picked instead fp-ts or other alternatives by some people.

I'm willing to implement this change, maybe it will unexpectedly become a key feature, just like MaybeAsync and EitherAsync did.

**Comment by bsander** [comment]
That's great to hear!

**Comment by gigobyte** [comment]
Done in `master`.
