### ISSUE TITLE
Better to not use point free style and parseInt in docs

### ISSUE THREAD

**Issue by captain-yossarian** [gigobyte/purify#261]
Hi, it is not recommended to use point free style with `map` and `parseInt`. Please look [here](https://medium.com/dailyjs/parseint-mystery-7c4368ef7b21)

**Comment by gigobyte** [comment]
You are confusing `Array.prototype.map` with the [Maybe#map](https://gigobyte.github.io/purify/adts/Maybe#map) function, which the example is demonstrating.
