### ISSUE TITLE
Meta: irc channel?

### ISSUE THREAD

**Issue by pyrho** [gigobyte/purify#268]
👋 ,

I've been using purify extensively lately and I'm loving it so thank you for that (: .
I'm pretty new to functional programing though and would love a place to exchange with other purify users.

What do you think @gigobyte ?

**Comment by gigobyte** [comment]
Tbh I don't really frequent programming slacks, discords, irc channels etc, you are free to create one if you want, but I wouldn't be there to help people.
If someone wants to reach out to me the Issues page here is perfectly fine.
Another thing to note is that the purify community is quite small, a handful of people, so I doubt there will be any active discussions in the channel.

**Comment by pyrho** [comment]
I understand, if you feel Issues is a better place to ask questions then it's settled :)
Maybe we'll reconsider IRC once the community grows.

That being said, I'll idle over at ##purify-ts on irc.freenode.net if anyone ever sees this and feels like popping over there (:
