### ISSUE TITLE
Docs still talk about `GetInterface` even though it is now `GetType`

### ISSUE THREAD

**Issue by anttti** [gigobyte/purify#270]
As stated in [the changelog](https://gigobyte.github.io/purify/changelog/0.16), `Codec` no longer has `GetInterface` but has `GetType` instead. [`Codec` documentation](https://gigobyte.github.io/purify/utils/Codec) still has multiple mentions of `GetInterface`, which threw me off for a minute.

**Comment by gigobyte** [comment]
You are right, I've updated the site. Thanks!
