### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by warpech** [gigobyte/purify#271]
Thank you for this great library.

Could you please clarify licensing:

1. The file https://github.com/gigobyte/purify/blob/e310d7ba63c1c4865fc20de428c14e9c045c49fa/LICENSE contains ISC license text
2. The file https://github.com/gigobyte/purify/blob/e310d7ba63c1c4865fc20de428c14e9c045c49fa/package.json says that the license is MIT

**Comment by gigobyte** [comment]
Sorry for the confusion, the LICENSE file is the real license, `package.json` says MIT because I believe that's the default license you get when you `npm init` and I haven't updated it.
