### ISSUE TITLE
Documentation examples incomplete

### ISSUE THREAD

**Issue by jkolyer** [gigobyte/purify#275]
I have struggled learning to use the package just from the documentation and the source code / tests.  

Having a working example with context is a much better way to learn.   I discovered your [other repo](https://github.com/gigobyte/ts-fullstack-starter.git), and this has filled the gap for me.  

I'm suggesting you provide new users a link to this repo, or something similar, to provide a contextual example.

**Comment by gigobyte** [comment]
I will probably link that repo as an example app at some point (won't do it now since it's incomplete).

What modules did you struggle with? `EitherAsync` I suppose? What examples do you think that the documentation should include?

**Comment by jkolyer** [comment]
I started using `Maybe` on existing project to reduce my if statements, but realized it's better to use comprehensively rather than piecemeal.  Now on a green-field refactoring I want to embrace as much as I can grasp.  So I would say all the modules are vague to understand from doc/source only.  Also I'm relatively new to FP (with no experience on a pure FP language).

A good prototypical example is user auth because it covers db errors, record not found, codecs, and async.  I'm following this pattern for my db access layer.  Examples applying to other application layers would be useful as well, such as UI.  

Ideally what I'd suggest is a comprehensive sample app (or template as you have now) that touches on a majority of the APIs for each module.  Then you can link to relevant portions from the documentation within the sample app.  This app would use the modules through the entire stack, from UI to DB layer.  This may be a tall order, but would be ideal.

Seeing the modules in a broader context, interacting with each other is really helpful.  They are designed to use together, and the current doc doesn't reflect this well atm.  I'm a big fan BTW.  This package fits nicely into my architecture and I love the simplicity and elegance of how the modules reduce imperative code.
