### ISSUE TITLE
{Maybe,Either}Async.alt, `other` value should be evaluated only if `this` is {Nothing,Left}

### ISSUE THREAD

**Issue by pyrho** [gigobyte/purify#277]
Hey,

I find somewhat confusing that the "other" in `{Maybe,Either}Async.alt` is not lazily evaluated.
As the documentation states:

> Returns the first `Just` between the future value of `this` and another future `Maybe` or future `Nothing` if both `this` and the argument are `Nothing`.

As I understand it, this should be used in the context where you try one asynchronous action, and if it fails you want to execute the other one, kinda like a fallback.

Consider the following theoretical example:

```typescript
import {Maybe, MaybeAsync, Just, Nothing } from 'purify-ts';

const fetchFromMaindatabase = () => {
    console.log('fetchFromMaindatabase');
return Promise.resolve(1);
};
const fetchFromBackupDatabase = () => {
    console.log('fetchFromBackupDatabase');
    return Promise.resolve(2)
};


(async () => {
    const valueMaybe = await MaybeAsync(fetchFromMaindatabase).alt(MaybeAsync(fetchFromBackupDatabase));
})()
```

With the [current implementation](https://github.com/gigobyte/purify/blob/867764b4ae4e7781b547b7dda1a7a6cd6db0ec45/src/EitherAsync.ts#L147), `Promise.all` is used to resolve both values simultaneously; resulting in both call "to the DB" being executed.
An alternative implementation could only evaluate the `other` value if `this` resolves to a Nothing/Left value.

What do you think about the following patch? If you agree I can submit a pull request.

```diff
diff --git a/src/MaybeAsync.ts b/src/MaybeAsync.ts
index de5a7b7..7d8dd29 100644
--- a/src/MaybeAsync.ts
+++ b/src/MaybeAsync.ts
@@ -116,8 +116,13 @@ class MaybeAsyncImpl<T> implements MaybeAsync<T> {
 
   alt(other: MaybeAsync<T>): MaybeAsync<T> {
     return MaybeAsync(async (helpers) => {
-      const [maybe, o] = await Promise.all([this.run(), other])
-      return helpers.liftMaybe(maybe.alt(o))
+      const thisResult = await this;
+      if (thisResult.isJust()) {
+          return  helpers.liftMaybe(thisResult as any as Maybe<T>);
+      } else {
+          const thatResult = await other;
+          return helpers.liftMaybe(thatResult);
+      }
     })
   }

```

Cheers.

**Comment by gigobyte** [comment]
You raise a good point and I agree. This applies to other methods as well and also `EitherAsync` so it's not a single change. I prefer if I fix the issue, there's no need for a PR.
