### ISSUE TITLE
Expected behavior when exceptions are raised ?

### ISSUE THREAD

**Issue by pyrho** [gigobyte/purify#280]
Consider the following code:

```typescript
import { Either } from "purify-ts";

(() => {
    Either.of<Error, number>(1)
        .map((v: any) => {
            // this line causes an exception
            v.someMethod();
            // nothing past this line gets executed
            return v + 1;
        })
        .ifLeft(() => console.log("an error occured"));
})();
```

In this case the whole "purify pipeline" is bypassed (the `ifLeft` here is not executed for example).

Wrapping most methods with a try/catch, where a `Left` would be returned in the event of a raised error would solve this issue.

**Comment by gigobyte** [comment]
`Either` does not handle exceptions, indeed, but I don't think that it should, it's slow enough as it is and it doesn't need extra (untyped, mind you) behaviour like this. You can use `Either.encase` if you expect something to fail.

**Comment by pyrho** [comment]
Thank you for your reply.

I guess `.chain` combined with `Either.encase` is good enough.
