### ISSUE TITLE
Can Codecs use generic types for encode/decode?

### ISSUE THREAD

**Issue by bsander** [gigobyte/purify#282]
Hi! I notice Codecs decode method signature takes an `unknown` argument type, and the encode method returns an `any`. The actual types being used aren't inferred and that makes working with types harder than it has to be. Could codecs instead use generic types for these methods instead?

**Comment by gigobyte** [comment]
> The actual types being used aren't inferred

Well that's kind of the point, isn't it 😄 When you decode a value you have no information about it, so `unknown` is the only usable type. When you encode a value you turn it into the value you want to send outside of your system, here we can be more flexible with the types since you know what you are returning.
I imagine `encode: <U>(input: T) => U` is what you are asking for? What is your usecase for this?

**Comment by bsander** [comment]
@gigobyte hi! Sorry for the late reply, I was on holiday back then and completely missed your response to my question.

Yes, that's exactly what I'm asking for. I can think of many usecases, one example would be an encoder that's using `JSON.stringify(...)`, which will always produce a string. If I then send that off somewhere, the receiver needs to re-establish that the value I'm sending is a string, which it could have inferred for free.

Similar for decode, for example when I'm retrieving a value from a database which I already know is a string, but I'd need to do some refinement in the codec (like validating minimum length). With inferred types I could only accept a string as input there, but currently I'll need to write that function to deal with all kinds of input, since it's typed as `unknown`.

Hope that clarifies it!

**Comment by gigobyte** [comment]
> I'm retrieving a value from a database which I already know is a string, but I'd need to do some refinement in the codec (like validating minimum length). With inferred types I could only accept a string as input there, but currently I'll need to write that function to deal with all kinds of input, since it's typed as unknown

In practice you always "know" what you'll be getting from an outside source, that's why 90% of the projects don't validate endpoints at all. Adding a 
```
string(input).chain(str => str.length > XX)
```
decoder is better than typeasserting the input to a string and then validating the length, it's kind of missing the point.

On `encode` I think I agree though, I changed the signature to `encode: <U>(input: T) => U` and everything worked fine, I think I'll include it in the next release.

**Comment by bsander** [comment]
I don't agree. There are many frameworks that do at least some form of validation before passing on the value. Express' bodyparser does that as well. GraphQL.js also provides some validation out of the box. It would be nice to be able to trust that, and it's different from just asserting. If the input values don't live up to their own typelevel promises, that's a different problem I think, and not one for Purify to solve.

**Comment by bsander** [comment]
@gigobyte I just wanted to ping you to make sure you saw my response, as I'm not sure replies to closed issues generate notifications. Maybe you can reopen the issue if it warrants further discussion, otherwise I'll let it rest.

**Comment by gigobyte** [comment]
What input validation are you expecting, string input is not a given, for example if you use `bodyparser` your endpoints will receive a javascript object.

> I'll need to write that function to deal with all kinds of input, since it's typed as unknown.
You don't actually need to handle non-string inputs, just `chain` the built-in string codec which is a line of code at most.

**Comment by bsander** [comment]
For strings this may be trivial, but that was just an example to keep it simple. Although I do maintain that even in these situations, the code that is added is not needed and therefore makes the whole application more complex and harder to read in general. The types don't "flow" anymore.

But let's talk about refinements. Right now I'm in a situation where I have to deal with an influx of messages, pick a subset that match a certain format (I can use decode `unknown -> T` here), store all of those, and then determine which of these messages indicate success of an operation and process that subset some more. If I'm going to use codecs like they are now, I'd need to decode again from `unknown -> S`, having to re-parse the entire message. Ideally I'd create a decoder here for `T -> S` and build on what I have already validated before.

This may not be too much of an issue for primitives and simple data structures, but when these messages grow large, or for example JWT validation enters the mix, and decoding actually means spending CPU cycles, I don't want to perform that same operation multiple times.

**Comment by gigobyte** [comment]
> store all of those, and then determine which of these messages indicate success of an operation and process that subset some more

By "store" do you mean in a DB or in-memory? If it's in a database then I understand why you might not want to run the same `decode` again, but at the same time you could just do `obj as MyObject` if you're certain of the type of the input.

**Comment by bsander** [comment]
Yes that's a workaround, but it's also bad practice, as you mentioned yourself as well earlier in this conversation. It also shouldn't be necessary to do if I could just wire the input type through the function signatures. The way it's set up now makes it hard to create more fine-grained codecs, or to compose multiple codecs into something bigger.

For the case where you wouldn't trust user input even if it's already typed, you could just set the codec input type to `unknown` explicitly to enforce proper re-validation.

**Comment by gigobyte** [comment]
I don't agree that it's a bad bractice. What is the difference between `input as MyObject` and `decode: (input: MyObject) => {}`, both assert a certain type, but they are just assertions. If you update your DB client library and it starts returning an object instead of a string both pieces of code are going to compile. It's not typechecked.

You can compose codecs through `Codec.custom` and chaining the original codec.
> For the case where you wouldn't trust user input even if it's already typed, you could just set the codec input type to unknown

The whole point of the `Codec` module is to validate inputs, if you skip all that it becomes just an overcomplicated if statement (i.e. to check string length and contents, limit number ranges and so forth). The case you are describing should be the main case for using the module.

**Comment by bsander** [comment]
> I don't agree that it's a bad bractice. What is the difference between input as MyObject and decode: (input: MyObject) => {}, both assert a certain type, but they are just assertions.

There is a huge difference. In the first case (`input as MyObject`), TS doesn't ask questions and treats the input as `MyObject`. In the second case (`decode: (input: MyObject) => {}`), TS will ensure the input argument is typed correctly, or fail compilation.

> If you update your DB client library and it starts returning an object instead of a string both pieces of code are going to compile. It's not typechecked.

This doesn't mean it's not typechecked, it just means that Typescript's ability to guarantee the types is limited and that escape hatches exist, for better or for worse.

If types are wrong, all bets are off. That's just something we'll have to live with if we use this language. The fault in that case lies with the DB client lib, and I don't think that's something purify should try to prevent. In the same vein I can also write a function `decode: (input: unknown): string => { return input as string }` to break typechecking using the current Codec implementation. Can't defend against that, we'll just have to accept that the trust we place in TS types is limited.

> You can compose codecs through Codec.custom and chaining the original codec.

Not without re-validating the input type, since it starts as unknown again. io-ts codecs get this right, they allow to compose codecs like this:

```typescript
const isValidPort = (n: number) => Number.isSafeInteger(n) && n > 1024;
const Port = t.refinement(t.union([t.number, NumberFromString]), isValidPort);
```

> The whole point of the Codec module is to validate inputs, if you skip all that [...]

I've never argued skipping validation. In my experience many validations happen in multiple stages, and I just want to be able to build on the work that was already done without having to typeassert.

**Comment by gigobyte** [comment]
```ts
const isValidPort = (n: number) => Number.isSafeInteger(n) && n > 1024;
const Port = t.refinement(t.union([t.number, NumberFromString]), isValidPort);
```
is the same (in behaviour) as
```ts
const validatePort = (n: number) => Number.isSafeInteger(n) && n > 1024 ? Right(n) : Left('Bad port');

const Port = Codec.custom({
  decode: (input) => number.decode(input).chain(validatePort),
  encode: number.encode
})
```
I agree there's more boilerplate because there's no `refine` utility like in io-ts, but the order of operations is pretty much the same. Both purify and io-ts will run the `number` codec first.

**Comment by bsander** [comment]
That indeed alleviates the pain somewhat, though it also removes some of the convenience of building composite codecs from simple building blocks.

Is there a way to find a middle ground and introduce a `partialDecode` or `optimisticDecode` method that takes the typehint into account, leaving the original `decode` method to deal with unknown inputs only?

**Comment by gigobyte** [comment]
I've made `encode` generic and this will be part of `0.16.2`
