### ISSUE TITLE
Codec.literal

### ISSUE THREAD

**Issue by tulsidas** [gigobyte/purify#283]
Is it possible to implement a literal codec similar to [this one](https://github.com/gcanti/io-ts/blob/master/Decoder.md#the-literal-constructor)?

The idea being that I can have:

```
type T = "a" | "b" | "c" | "d";

Codec.interface({
   t: literal(T)
})
```

rather than:

```
Codec.interface({
   t: oneOf([exactly("a"), exactly("b"), ...])
})
```

**Comment by gigobyte** [comment]
Well your first example is definitely not possible (you used a type as a value in the definition of the codec 😄 ), but I like the io-ts version where you can do `literal('a', 'b', 'c', 'd')`, which would be `exactly` in purify.

**Comment by tulsidas** [comment]
If I already have a type which has a string literal union, how can I reuse that information instead of copy-pasting it?

```
interface X {
   a: string;
   b: number;
   c: "a" | "b" | "c" | "d" | "e";
}
```

Is there a way to define a codec for the c property values ? In pseudocode:

```
Codec.interface({
  prop1: string,
  prop2: optional(string),
  prop3: literal(X.c),
});
```

**Comment by gigobyte** [comment]
That's not possible, TypeScript has no runtime. You can use an enum instead, that generates a real runtime object which you can pass to purify:
```typescript
enum C {
  a = 'a',
  b = 'b',
  c = 'c',
  d = 'd'
}

Codec.interface({
  prop: enumeration(C)
})
```

**Comment by pvarga-dni** [comment]
FWIW I like the idea of supporting `exactly('a', 'b', ...)`. This would be nice to have.

@tulsidas As for avoiding copy-pasting, I think in general, going in the opposite direction is a better idea: have a `Codec` definition first, then derive the TypeScript type from that:

```ts
const x = exactly(1) // Just an example
type y = GetType<typeof x>
```
