### ISSUE TITLE
A more readable wrapper for Either?

### ISSUE THREAD

**Issue by kodeFant** [gigobyte/purify#287]
Hi, I have been using your library for a while now and I really like it 👍 

When introducing the Either type to a team, it creates some confusion. Left, Right and adding some async on top of it confuses those who are on the fence a bit.

I was wondering if you had some thoughts about making a wrapper for it with more semantic syntax? I am for example a big fan of Elm's rewrite of Either.

https://package.elm-lang.org/packages/elm/core/latest/Result#Result

Example:

```typescript
const port: number = getPort() // Result<Error, number>
    .ifError((e) => loggingService.log(e.message))
    .map(parseInt)
    .orDefault(8080)
```

or for example how I would use it in React:

```typescript
user.caseOf({
  Error: (e) => <div>You are not logged in. Error message: {e}</div>,
  Ok: (user) => <UserProfile data={user} />
})
```

**Comment by pyrho** [comment]
These examples can be written with purify right now:


```typescript
import { Either, EitherAsync } from 'purify-ts';

function getPort() {
    return Either.of<Error, string>('42');
}

const port = getPort()
    .ifLeft(error => console.log('Error in getPort' + error.message))
    .map(s => parseInt(s, 10))
    .ifLeft(_ => console.log('Cannot parseInt'))
    .orDefault(42);

Either.of<Error, string>('a user').caseOf({
    Left: () => '<p>an error occured</p>',
    Right: () => '<p>Welcome</p>'
})

function getPortAsync() {
    return EitherAsync<Error, string>(async () => {
        const someData = await getSomeAsyncData();
        return 42;
    });
}

// Pretty much the same if you have asynchronous calls, just use EitherAsync

const port = await getPortAsync().ifLeft(console.log).map(parseInt).orDefault(42)

```

I feel like I may have misunderstood your question(s), so please clarify if this doesn't help.

As for:
> and adding some async on top of it confuses those who are on the fence a bit.

If you have asynchronous call to make you should use [EitherAsync](https://gigobyte.github.io/purify/adts/EitherAsync) not `Either`.

**Comment by KevinMGranger** [comment]
@pyrho the point is that "Left / Right" is more confusing to newcomers than "Error / Ok"

**Comment by pyrho** [comment]
Well if the newcomers are coming from Haskell, they'll feel right at home; see Haskell's [Either](https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Either.html).

But if they're coming from Rust, then `Result<Ok,Error>` may feel more familiar.

My point being that it's really a question of opinion and background; but I'm really just spitballing here. Let's wait for the owner's opinion;  that was just my own  (:

**Comment by gigobyte** [comment]
Implementing a wrapper is trivial one-liner so I would have to agree with @pyrho here:
```typescript
// Result.ts
export { Either as Result, Left as Err, Right as Ok } from './Either'
```
The problem is that you will still get `Either` in your editor and even if you manage to overcome that methods like `mapLeft` will still be there to confuse people. Maintaining a separate `Result` module that is 1:1 with `Either` but with different names and wording is just not worth it.

**Comment by sporto** [comment]
I agree that using Err and Ok is a more readable than Left and Right. I use some languages that put the error at the right (OCaml, Gleam). So at least for me `.mapLeft` is not obvious, `mapError` is straighforward.

**Comment by kodeFant** [comment]
For Haskell, Elm or Rust developers it should be very familiar. But for Java and JavaScript developers, these are entirely new concepts, and my wish is to win them over to functional thinking. I guess it all depends on the target group of the library :)

I am getting the sense that they really like the library, and the Codec pattern, but Left and Right adds a bit of a cognitive load for newbies. 

I am personally totally fine with Left and Right since I already love functional programming.

I understand managing different modules with same logic is a bit too much. Just my five cents, thanks for the feedback and the discussion :)
