### ISSUE TITLE
Use of Maybe as a return type - Nothing complains

### ISSUE THREAD

**Issue by mustafaekim** [gigobyte/purify#29]
Hi,

The function below, which is expected to return a Maybe<Card> cannot return Nothing. I am getting the error: **Type 'Card' is not assignable to type 'never'**

Both returning Maybe.empty() and returning Nothing result with the same error.

What am I doing wrong here?

```ts
import { Maybe, Just, Nothing } from "../../functions/src/common/model/utility"
import { Card } from "../../functions/src/common/model/authentication";

export function getCardFromLocaleStorage(): Maybe<Card> {
    var cardJSON = localStorage.getItem("guestCard") || localStorage.getItem("userCard");
    if (!cardJSON) return Maybe.empty();
    try {
        return Just(JSON.parse(cardJSON) as Card)
    }
    catch (err) {
        return Nothing
    }
}
```

**Comment by gigobyte** [comment]
Strange, it compiles just fine when I try it out, there shouldn't be an error.

Maybe you're exporting the wrong things in `"../../functions/src/common/model/utility"`, you can check that out.

**Comment by mustafaekim** [comment]
3.0.1
