### ISSUE TITLE
Expose Codec.interface as a top-level export like other "Codec factories"

### ISSUE THREAD

**Issue by pvarga-dni** [gigobyte/purify#290]
Hi,

This is very much just a developer experience issue, but the first time I checked out `purify-ts`, I didn't find `Codec.interface()`, because I've only looked at what's available in `import { ... } from "purify-ts"`.

The fact that `record()`, `array()` etc. are there sort of assured me I'm looking in the right place, and I just went with `io-ts` instead solely because of this, concluding that Purify doesn't have this basic functionality yet.

Of course I could have RTFM'd 🙄, but I think `interface()` should (also) be exported at the top-level, if for no other reason then to be consistent.

**Comment by gigobyte** [comment]
Thanks for your feedback!

There is an explicit "How to import" section at the top of the docs, so your experience seems to be more of an edge case 😅 .

I think exposing `interface` as a named export will make things more confusing (Is `Codec.inteface` the same as `interface`? There are no examples of just `interface` used in the docs, is it okay if I use it? etc), so I'm going to refrain from doing that.
