### ISSUE TITLE
Decode error for interface/record intersection when properties overlap

### ISSUE THREAD

**Issue by tokland** [gigobyte/purify#291]
Is there a way to make this work?

```typescript
import { Codec, string, number, intersect, record } from "purify-ts/Codec";

export const userCodec = intersect(
    Codec.interface({ id: string, name: string }),
    record(string, number) // attributes
);

console.log(
    userCodec
        .decode({ id: "123", name: "Some Name", attr1: 1, attr2: 2, attr3: 3 })
        .caseOf({ Right: data => JSON.stringify(data), Left: error => error })
);
// Problem with the value of property "id": 
// Expected a number, but received a string with value "123"
```

**Comment by gigobyte** [comment]
This is not possible because it's not a valid TypeScript construct either. For example this gives an error:
```ts
// Property 'id' of type 'string' is not assignable to string index type 'number'.ts(2411)
// Property 'name' of type 'string' is not assignable to string index type 'number'.ts(2411)
type Test = { id: string; name: string; [key: string]: number }
```
You can trick the typesystem by using an union:
```ts
type Test = { id: string; name: string } & Record<string, number>
```
but then when you try to construct a value of that type it's not possible:
```ts
// Type '{ id: string; name: string; }' is not assignable to type 'Test'.
//  Type '{ id: string; name: string; }' is not assignable to type 'Record<string, number>'.
//    Property 'id' is incompatible with index signature.
//      Type 'string' is not assignable to type 'number'.ts(2322)
const a: A = { id: '', name: '' }
```

**Comment by tokland** [comment]
You're right! I was fooled because the type looks ok, but, as you say, you cannot create values for that type (relevant: https://github.com/microsoft/TypeScript/issues/17867). 

So I simply cannot use purify to validate an object of this kind? That's an external API I have no control over.

**Comment by gigobyte** [comment]
The type you want is
```ts
type User = { id: string; name: string } & Record<string, string | number>
``` 
because the value can be either a string (id and name) or a number.

Translating that into a codec, you can try out
```
export const userCodec = intersect(
  Codec.interface({ id: string, name: string }),
  record(string, oneOf([string, number]))
)
```
Let me know if it fails if you call it something like `name: 0`, I haven't tested that out so it might be buggy.

**Comment by tokland** [comment]
That's close: `{ id: 123, name: "Some Name", attr1: 1 }` is not validated, but `{ id: "123", name: "Some Name", attr1: "1" }` is.

**Comment by gigobyte** [comment]
That's true, I guess that the best you can do unfortunately.

**Comment by tokland** [comment]
It's ok, I can live with that. I guess we can close the issue until TS solves it somehow. Thanks for your time, @gigobyte.
