### ISSUE TITLE
Maybe.all & Either.all

### ISSUE THREAD

**Issue by AlexandruGG** [gigobyte/purify#294]
Hello! Thank you for the work put in this library and the documentation, which is really easy to follow compared to others.

In the company I work for we currently use the `Option` and `Result` types from [space-monad](https://github.com/AlexGalays/space-monad), but I've been looking at **purify** as an alternative.

Is there an equivalent way to do the `Option.all` and `Result.all` operations that space-monad [provides](https://github.com/AlexGalays/space-monad#optionalloptionsorvalues)? (for Maybe and Either)

```TS
const some = Option.all([
  Option(10),
  20,
  Option(5)
])
// some === Some([10, 20, 5])

const none = Option.all([
  Option(10),
  None,
  Option(5),
  null
])
// none === None
```

Sorry if I missed it in the docs, but I couldn't find any easy way to do this!

**Comment by gigobyte** [comment]
You're looking for [`Either.sequence`](https://gigobyte.github.io/purify/adts/Either#sequence). Unfortunately `Maybe.sequence` exists in master, but it's not released yet.

**Comment by AlexandruGG** [comment]
Ah, excellent! Yes, that's exactly what I was looking for, thank you.

Looking forward to the `Maybe.sequence` release.
