### ISSUE TITLE
How to combine Eithers smoothly?

### ISSUE THREAD

**Issue by hellos3b** [gigobyte/purify#301]
I'm not sure if this is just me misunderstanding FP or if it's something that the library can possibly help with

I have data coming from two different sources, where the second relies on the first, and I'm having a hard time figuring how I'm supposed to use the data from both Eithers together

For example, I have a `!profile` command in a chat bot that does the following:
1. Gets a `User` object from a database
2. Use the user's refresh token to fetch an `Activity` from an external web service. 
3. Respond with a card or an error message

Models:

```ts
interface UserDTO {
  id: string;
  username: string;
  refreshToken: string;
}

interface Activity {
  id: string;
  title: string;
}
```

Controller:

```ts
function onMessage(fromId: string) {
  const userAsync: EitherAsync<Error, UserDTO> = fetchUserById(fromId);

  const activityAsync: EitherAsync<Error, Activity> = userAsync
    .chain(createClient)
    .chain(_ => _.getLatestActivity());

  // Need help here combing the two async Eithers into a message 
  // example - `${userAsync.username}'s last activity was ${activityAsync.title}`
  const parsed: Either<Error, Message> = /** Use the two asyncs to create one Either */;

  const reply: Message = parsed
    .chainLeft(err => Right(formatError(err))
    .extract();

  bot.send(reply);
}
```

Tried to keep my example simple, but the combination can have more than 2 responses and the Message object is more complex than a string. Is there a recommended way to doing this, or do I have just have to `await`, `ifLeft()` + early return and `extract()` manually?

**Comment by hellos3b** [comment]
Okay, after spending the last few hours reading up on FP principles, I came across this [article on Applicative Functors](https://mostly-adequate.gitbook.io/mostly-adequate-guide/ch10) which goes over `ap` and a `liftA2` function.

I was able to write a helper for EitherAsync, is there any chance we can get something like this native? Combing Eithers comes up often

```ts
const liftA2 = <E, A, B, C>(fn: (a: A) => (b: B) => C, a: EitherAsync<E, A>, b: EitherAsync<E, B>) => b.ap(a.map(fn));

// Display an over view of stats 
export async function profile(message: Message) {
  const dto = Users.findOne({discordId: message.author.id});

  const activities = dto
    .chain(createClient)
    .chain(client => client.activities({}));

  const embed = liftA2(createEmbed, dto, activities);
}
```

**Comment by gigobyte** [comment]
For this kind of problem I prefer using the async/await mode in EitherAsync, there's nothing wrong with `liftA2`, it's just personal preference.

```ts

function onMessage(fromId: string) {
  EitherAsync(async ({ fromPromise }) => {
    const user: UserDTO = await fromPromise(fetchUserById(fromId).mapLeft(formatError))
    const activity = await fromPromise(createClient(user).chain(_ => -.getLatestActivity()).mapLeft(formatError))

    const reply = `${user.username}'s last activity was ${activity.title}`

    bot.send(reply);
  }).run()
}
```
Let me know what you think,
