### ISSUE TITLE
Cancel execution about EitherAsync

### ISSUE THREAD

**Issue by Aetet** [gigobyte/purify#305]
Hello!
Thanks for library! I have one question about API of EitherAsync.

When I make new request for data, I can switch route. So old request data will be stale.
To prevent this I want to cancel .then handler and doesn't invoke it at all.

Is there any mechanic about cancelling EitherAsync or not?

**Comment by gigobyte** [comment]
Unfortunately, there is nothing custom within the library. EitherAsync is basically a wrapper around Promises so whatever works with Promises will work with EitherAsync as well (even 3rd-party libraries).

**Comment by Aetet** [comment]
Ok. Got it, thanks!
