### ISSUE TITLE
Resolving a MaybeAsync to Nothing

### ISSUE THREAD

**Issue by pyrho** [gigobyte/purify#308]
If my wrapped promise returns a null value I want  to return a `Nothing`. 
That's how I'm doing right now; is there a better/more idiomatic way of achieving this?

```typescript
// f: () => Promise<string|null>;

MaybeAsync(f).chain(x => Promise.resolve(Maybe.fromNullable(x)));
```

**Comment by gigobyte** [comment]
Nope, there isn't. It looks like a pretty rare case, so I'm not inclined to include it in the library as a util, but you can use it if you need to do it a lot in your codebase.
```ts
MaybeAsync(f).chain(async x => Maybe.fromNullable(x));
```

**Comment by pyrho** [comment]
> It looks like a pretty rare case

Not in my experience, I find myself having that issue quite often (with MaybeAsync and EitherAsync).

In this specific example I am wrapping calls to a Redis database (via the [IOredis](https://github.com/luin/ioredis) lib).

I'm trying a `pop` a queue, and Redis replies with a `nil` value when the queue is empty.
I want a `Just` if a value exists in this queue, or a `Nothing` if the queue is empty.

That doesn't seem like a far fetched scenario.


That being said, I also think a plus to keep the "core" purify library as lean as possible; and implement this kind of "extra" features as external utils.
