### ISSUE TITLE
Array schema incorrect?

### ISSUE THREAD

**Issue by vesse** [gigobyte/purify#309]
The way [JSON schema is created from an array](https://github.com/gigobyte/purify/blob/12cd0394f8990166fc864fe4ed30c457da945beb/src/Codec.ts#L363-L366) is incorrect – the created schema is for a tuple, not for a list.

I'm trying to use a `Codec` in an array like this:

```typescript
const Item = Codec.interface({
  id: number,
})
type Item = GetType<typeof Item>

const ItemList = array(Item)
type ItemList = GetType<typeof ItemList>

const itemListSchema = ItemList.schema()
```

which produces JSON schema like this:

```javascript
{
  type: 'array',
  items: [
    {
      type: 'object',
      properties: { id: { type: 'number' } },
      required: [ 'id' ]
    }
  ]
}
```

and when I use this as the response schema in Fastify it rejects responses with more than one item (ie. `[ { id: 1 } ]` is fine, but `[ { id: 1 }, { id: 2 } ]` fails). I believe this is because passing an array in `items` of the schema means [tuple validation](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation). For [list validation](https://json-schema.org/understanding-json-schema/reference/array.html#list-validation) the `items` should hold an object, ie. the `schema` implementation for `array` to stand for a list of items should be

```
schema: () => ({
  type: 'array',
  items: codec.schema()
})
```

**Comment by gigobyte** [comment]
I see. At first I thought that this is something new from draft 7 (purify is draft 6 compatible), but after running your example through a [validator ](https://www.jsonschemavalidator.net/)it worked.

Considering that there might be discrepancies between newtonsoft's validation and ajv's validation (the library used inside fastify), the solution would be to write a lot of test cases to make sure purify works with ajv.

**Comment by vesse** [comment]
Yeah, for now I just added

```javascript
schema: {
  response: {
    200: {
      type: 'array',
      items: Item.schema(),
    },
  },
},
```

because at the moment it is only this single place where I need the schema.

And actually, with default settings at least `ajv` accepts a list for the schema which may be it being just tolerant, but the problem was with `fast-json-stringify` which is used by Fastify for the responses and their schemas. 

So just in case someone is interested, the schema works with `ajv` (and this is why I was very confused about the problem because I couldn't reproduce that when running `ajv` myself)

```typescript
import Ajv from 'ajv'

const ajv = new Ajv()
const validate = ajv.compile({
  type: 'array',
  items: [
    {
      type: 'object',
      properties: { id: { type: 'number' } },
      required: ['id'],
    },
  ],
})

// No errors produced, validate.errors is null too
const result = validate([{ id: 1 }, { id: 2 }])
```

but it does not work for `fast-json-stringify`

```typescript
Error: Item at 1 does not match schema definition

const stringify = fastJson({
  type: 'array',
  items: [
    {
      type: 'object',
      properties: { id: { type: 'number' } },
      required: ['id'],
    },
  ],
})

// This throws Error: Item at 1 does not match schema definition
stringify([{ id: 1 }, { id: 2 }])
```

**Comment by gigobyte** [comment]
Interesting, could this be a bug in `fast-json-stringify`? I trust newtonsoft and ajv way more to handle that kind of validation.

**Comment by vesse** [comment]
No, it's just that Fastify uses `ajv` 6.x which does not have `strictTuples` configuration and it allows tuple definition for arrays too (see eg. ajv-validator/ajv#1417), whereas `fast-json-stringify` does not allow that. With never `ajv` there would be a warning displayed.

**Comment by vesse** [comment]
Returning to this, I tested with latest `ajv`

```typescript
const schema = Codec.interface({
  array: array(string),
  nonEmpty: nonEmptyList(string)
}).schema()

const arrayData = {
  array: ['cat', 'pretty'],
  nonEmpty: ['dog', 'hairy']
}

const tupleData = {
  array: ['cat'],
  nonEmpty: ['dog']
}
```

and with default settings it prints

```
strict mode: "items" is 1-tuple, but minItems or maxItems/additionalItems are not specified or different
strict mode: "items" is 1-tuple, but minItems or maxItems/additionalItems are not specified or different
```

for the `arrayData` whereas `tupleData` passes, and if Ajv is created with `strictTuples: true` it throws the warning.

**Comment by gigobyte** [comment]
Fixed.
