### ISSUE TITLE
Maybe.chainFalsy?

### ISSUE THREAD

**Issue by tulsidas** [gigobyte/purify#335]
I usually write something like this:

`const number = Maybe.fromFalsy(obj1?.obj2?.records)
      .chain(records => Maybe.fromFalsy(records.find(elem => elem.boolProperty)))
      .map(elem => elem.numProperty)
      .orDefault(0);`

Since there already exists `chainNullable`, does it make sense to have `chainFalsy`? Or is there a better way that I'm missing?

**Comment by gigobyte** [comment]
There's nothing inherently wrong with `chainFalsy`, it's just that I'm trying to limit the API to things that would be too cumbersome to write without having a built-in method.

In your case, `Array.find` returns undefined if an element is not found so you can just use `chainNullable`:
```ts
Maybe.fromFalsy(obj1?.obj2?.records).chainNullable(records => records.find(elem => elem.boolProperty)))
```

**Comment by tulsidas** [comment]
List.find I never saw it before, thanks!
