### ISSUE TITLE
Wrong types with unhandled promise rejection

### ISSUE THREAD

**Issue by davazp** [gigobyte/purify#340]
Hi, first of all,  thanks for the work on purify.  It is a very nice library with a lovely API!

So, I was playing around with it, and found that in case of unexpected promise rejections, the inferred type of `.run()` will be wrong.  Now, this can be acceptable if `EitherAsync` **assumes that promises are never rejected**.   That should be very emphasized in the documentation.

I think this is unfortunate, though.  Because it will make errors difficult to catch.  If the user forgets to wrap a single external function, you can end up with a variable of type `Either<...>` which is actually something else.   As in the example, I attach below.

## A proposal

A maybe nicer solution, though backward-incompatible,  could be to allow `.run()` to reject if a promise is rejected. (other than with `fromPromise`, which we can tag to identify and keep it safe).

That way,  `.run()` will resolve to Either in regular cases,  and reject in the presence of unhandled errors.

## The example

```typescript
import { EitherAsync } from "purify-ts";

interface MyError {
  code: string;
}

async function external() {
  throw new Error("unexpected");
  return true;
}

const getData: EitherAsync<MyError, boolean> = EitherAsync(
  async ({ fromPromise }) => {
    const result = await external();
    return result;
  }
);

getData
  .run()
  .then((result) => {
    result.caseOf({
      Left: (err) => {
        console.log("left", err);
      },
      Right: (value) => {
        console.log("right", value);
      },
    });
  })
  .catch((err) => {
   // Instead,  of returning left, we could reject the promise and end up in this case to catch it.
    console.log({ err });
  });

```

**Comment by davazp** [comment]
@gigobyte there is another alternative, that is to keep the `EitherAsync<L,R>` but allow `.run()` to reject when this case happens. 

Basically,  `.run()` will only reject if the user has made a mistake somewhere and a promise is being rejected.  It is not intended to be use for error handling mechanism, but as a "panic" situation.  If `.run()` rejects, you can look at which error you are not handling correctly and make it explicit in the Left of your error type.

**Comment by gigobyte** [comment]
How would you know which errors to reject and which to wrap in a Left? This would only work if none of the exceptions are wrapped, but this adds more boilerplate if you actually want to wrap them in a Left. The benefit of `EitherAsync` is that I can wrap a library (DB client, WS, HTTP etc) and call it knowing that I will always need to handle the exceptions.

**Comment by davazp** [comment]
> How would you know which errors to reject and which to wrap in a Left? 

If I understand correctly, there are 2 sources of rejections:
- Helpers `fromPromise / fromEither`
- Unhandled promises

I am missing something?  Let say we `await` on another EitherAsync without fromPromise. This resolving to Either.  But in that case, a rejection is still unexpected and so "unhandled".

If this is true, then we mark the rejections of `fromPromise` and other helpers.  Say,  they internally throw something like

```
{
   __tag: 'internal_rejection',
  error: E
}
```

This special value would signal `.run()` that we know this error is expected, handled, and is actually guaranteed to have the right type.  So `.run()` can take it and return it as the `Left` value of the result, instead of rejecting.

> This would only work if none of the exceptions are wrapped, but this adds more boilerplate if you actually want to wrap them in a Left. The benefit of EitherAsync is that I can wrap a library (DB client, WS, HTTP etc) and call it knowing that I will always need to handle the exceptions.


Sorry I am not sure if I follow this.  Why would this be more boilerplate?   What I have in mind (which may be not feasible) would not change the code that the user has to write in any case, right?

**Comment by davazp** [comment]
> I am missing something?

I reply myself.   I guess I am missing awaiting on `Promise<Either<...>`. instead of other `TaskAsync`!!!

That is unfortunate.  Ok.. any idea to workaround that? 🤔

**Comment by gigobyte** [comment]
I guess I prefer the current design which is to turn exceptions into `Left`. You can even use `EitherAsync` without using any of the helpers, just returning values and throwing exceptions like you would normally, but when you await something you have to handle the `Either` which is a great benefit to me.

**Comment by davazp** [comment]
Fair enough!  🙂 

Well hopefully the finding helps others to prevent some issues and ensuring they don't throw things with wrong types.

Thanks for the discussion.  Please feel free to close the issue!

**Comment by gigobyte** [comment]
I'll still add it as a note to the docs, it's not a minor detail. 😄
