### ISSUE TITLE
Either - add aliases for "error" and "success"

### ISSUE THREAD

**Issue by MartinRamm** [gigobyte/purify#348]
Hello,

First of all thank you very much for your work, I will be using it in a new FE that I am currently building.

I am trying to keep the learning curve for other programmers as low as possible, while using the very useful features functional programming offers. Hence, I would like to propose one change to the `Either` and `EitherAsync` modules: Currently, by convention, "Right is right", meaning that success is stored on the Right and failure is stored on the Left" as stated in your docs. Instead of having to know this, I would propose adding aliases to functions that encapsulate this knowledge in the code, making it easier to understand it without having to read the documentation.

For example, the constructor `Left` would get an alias for `Error`, the function `lefts` would get `errors`, `isLeft` `isError`, etc. IMHO this would make the library even more "practical", which seems to be one of the driving forces you have as an author.

Happy to discuss this proposal further, or even help to implement it.

Thanks

-Martin

**Comment by gigobyte** [comment]
There have been proposals like this before, and if it was in the beginning of the library I would've implemented it, but I think that ship has sailed. 

I agree that `Result` and `Error/Success` are easier to understand at _first_, but if you want to have deeper understanding of it, there's an enormous amount of information online about `Either`, so it's exactly obvious which is better for beginners.

**Comment by MartinRamm** [comment]
While I understand your point, I think especially for newcomers to the concepts, this is a steep learning curve they have to climb before using `Either` (unless they already know it from other libraries or languages). Using aliases wouldn't hinder anyone using `Left` or `Right` in the code, but the dev/dev team could decide for themselves what they prefer using (i.e. make it a code convention to use `Left` or `Error`).

You could also argue that someone who already knows the `left` and `right` concept from other libraries or languages can adapt quicker to `success` and `error`, compared to someone who never worked with it before.

**Comment by gigobyte** [comment]
The argument is not that it's familiar to people coming from other libraries or languages, the point is that if you don't understand the documentation of purify, you can still google for other resources.

I don't want to repeat myself so I'll just link an older issue: https://github.com/gigobyte/purify/issues/287
