### ISSUE TITLE
Add es6 transpiled version to npm

### ISSUE THREAD

**Issue by libre-man** [gigobyte/purify#362]
(If this issue is unwanted please remove)

I know that with #293 for short while there was a ES6 transpiled version of purify available. The main advantage that had for us was that `async` and `await` wasn't transpiled, which makes debugging with tracebacks way better. I don't know why this was removed, but we would really appreciate it if were possible again to use a ES6 version of this library.

**Comment by gigobyte** [comment]
It was removed because it didn't work, at least I couldn't compile es6 code with `tsc`. If you can figure out a setup a PR would be great.

**Comment by libre-man** [comment]
Hmm weird, because version 0.16.1 (I think) contained a `es` folder that worked perfectly for us.

**Comment by gigobyte** [comment]
Aah, yes I see what you mean. Looks like `0.16.2` is a bad release, I'll release a new version with the `es` modules.
