### ISSUE TITLE
strict mode for Codec

### ISSUE THREAD

**Issue by tulsidas** [gigobyte/purify#368]
I think it would be benefitial to have a way to "strict" decode a JSON, meaning that the **only** the specified values should exist on the object, and if there is any other property, reject it.

In my particular use case, I have something like:
`
Codec.interface({
   billingAddress: address,
   shippingAddress: optional(address),
})
`

But if the user makes a typo and passes _shipingAddress_  (missing the extra p) that would be a valid input but in reality the shipping address will be missing.

Makes sense?

**Comment by gigobyte** [comment]
I'm generally not a fan of this, crashing on extra properties just means that the code is not forward compatible. I've posted a codec combinator for `strict` before though: forward-compatible
