### ISSUE TITLE
Add `finally` like method to `EitherAsync`

### ISSUE THREAD

**Issue by libre-man** [gigobyte/purify#376]
Sometimes it is useful to always run a certain action at the end of request, like scheduling a timer. Currently with `EitherAsync` this is kinda annoying as you need to do something with both `ifLeft` or `ifRight`. A normal promise has `finally` which does exactly what I would like.

**Comment by gigobyte** [comment]
Would `finally` return another `EitherAsync` or a Promise?

**Comment by libre-man** [comment]
Ideally an `EitherAsync` as you can always make an promise out of it pretty easily.
