### ISSUE TITLE
Async effects & EitherAsync

### ISSUE THREAD

**Issue by tulsidas** [gigobyte/purify#378]
What is the proper way to run async functions in EitherAsync as effects (i.e. ifLeft/ifRight)? In pseudocode:

```
EitherAsync.liftEither(someEither)
        .ifRight(request => saveToDB(request))
        .chain(...)
```

Where saveToDB is an async function, for example:
`async function saveToDB(request: ...): Promise<void>`

The idea is to save to the DB **before** proceeding with the chain and so forth

As far as I know, that pseudocode above will not wait for saveToDB to complete and I was unable to make it so by using await inside the ifRight

Any hints?

Thanks

**Comment by pyrho** [comment]
Why not return an `EitherAsync` in `saveToDB` ? Or just wrap it into one if you cannot modify `saveToDB`. 
Then you could chain it, *and* handle potential error of `saveToDB` in your either chain.

**Comment by gigobyte** [comment]
I imagine you want something like this?
```ts
EitherAsync.liftEither(someEither)
    .chain(async request => {
        await saveToDB(request)
        return request
    })
    .chain(...)
```
Alternatively:
```ts
EitherAsync(({ liftEither }) => {
    const request = await liftEither(someEither)
    await saveToDb(request)
    ...
})
```

**Comment by tulsidas** [comment]
but to chain means to transform the original value, no? 

If there is no way to do it with `ifRight` then I'll resort to do it that way but it seems awkward

**Comment by gigobyte** [comment]
`chain` is for chaining any async function, it's doesn't really matter what do you inside the function. `ifRight` is mainly for running side effects that are required by a 3rd party library (like `res.send` in express) or for debugging/logging.

**Comment by tulsidas** [comment]
Got it, thanks! 👍
