### ISSUE TITLE
Update site to Gatsby 2

### ISSUE THREAD

**Issue by gigobyte** [gigobyte/purify#38]
Currently it crashes when starting `yarn develop` (which is just an alias to `gatsby develop`) with the new version of Gatsby.

To get started you need to:
* `cd` into the `site` folder in this project
* make sure everything builds correctly by running `yarn develop`
* update the Gatsby dependency with yarn

**Comment by mikaoelitiana** [comment]
I will work on this issue

**Comment by gigobyte** [comment]
Everything seems to be working correctly, thank you!
