### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by adomokos** [gigobyte/purify#380]
I pulled the latest source code and tried to build it locally.
I ran:

```
npm install
npm test
```

Received errors like this:

```
 FAIL  src/List.test.ts
  ● Test suite failed to run

    Cannot find module 'http-proxy-agent'
    Require stack:
```

Installed the missing libraries `http-proxy-agent` and `https-proxy-agent`, and `npm test` worked like a charm.

Should these libraries be added as dependencies or dev-dependencies? 

Node version: `v12.18.2`

**Comment by gigobyte** [comment]
Hmm it works for me, `purify` has zero runtime dependencies so I don't know where you get this `http-proxy-agent` error from.
```
"dependencies": {
    "@types/json-schema": "7.0.7"
  }
```
