### ISSUE TITLE
ability to compare Either result with strict or non strict equality

### ISSUE THREAD

**Issue by emiliauskas-fuzzy** [gigobyte/purify#393]
I'm not sure if it's even possible, but when writing unit tests I like to put Either result for equality assertion, but now I get something like:

```
assert.equal...
//results
AssertionError: expected Right("COMPLETED") to equal Right("COMPLETED")
```
I know there is a separate func equals for that but the unit test lib wont print the diff of expected and actual value. The workaround for me now is to use orDefault, but that can be tiresome after a while.

I'm using mocha lib for this, maybe there's a better workaround I could use. Thanks! I really appreciate the lib as it makes typescript a bit more fun to work with esp. with lots of api call handling.

**Comment by gigobyte** [comment]
I haven't used mocha/chai in years but surely there is a method to compare objects structurally, like there is a `toEqual` alternative to `toBe` in jest. I don't have a problem with testing Either [with jest](https://github.com/gigobyte/purify/blob/master/src/Either.test.ts).

If you can't fix this issue:
```ts
expect(Right("COMPLETED").equals(Right("COMPLETED"))).toEqual(true)
// or
expect(Right("COMPLETED").extract()).toEqual(Right("COMPLETED").extract())
```

**Comment by emiliauskas-fuzzy** [comment]
hey, thanks for the tips! interestingly expect does work, while assert doesn't for whatever reason, which I think is related to how mocha interprets the values (due to mocking I guess).
```
expect(Right(JobStatus.INPROGRESS).equals(Right(JobStatus.INPROGRESS)))	// works
// assert.equal(Right(JobStatus.INPROGRESS), Right(JobStatus.INPROGRESS))	// gives AssertionError: expected Right("INPROGRESS") to equal Right("INPROGRESS")		
```			
oh and just noticed in readme there's actually chai extension, probably solves the above issue, as I was using chai.assert actually.

btw, to avoid new issue, I was meaning to use Codec for json parse error handling, but I'm not sure if there is any way of inferring the existing type when creating a codec to be used for decoding? Just so to avoid repeating type definition in the interface func. Cheers!

**Comment by gigobyte** [comment]
>  but I'm not sure if there is any way of inferring the existing type when creating a codec

You mean [this](https://gigobyte.github.io/purify/utils/Codec#helper-GetType)?

**Comment by emiliauskas-fuzzy** [comment]
this is for type inference, but I was thinking vice versa having a type
definition and creating a codec for it

**Comment by gigobyte** [comment]
That's not possible, TS doesn't have a runtime.

**Comment by emiliauskas-fuzzy** [comment]
I see, I guess it would require some macros/meta level ability to access types, anyway, thanks for updates
