### ISSUE TITLE
Typescript error on EitherAsync.chain example

### ISSUE THREAD

**Issue by mahulst** [gigobyte/purify#412]
On this page https://gigobyte.github.io/purify/adts/EitherAsync#instance-chain
The example will give a typescript error:
```
EitherAsync(async () => 5).chain(x => EitherAsync(async () => x + 1)).run()

EitherAsync(async () => 5).chain(async (x) => x + 1).run()
```

`Type 'Promise<number>' is not assignable to type 'PromiseLike<Either<unknown, unknown>>`

If I change the example to return an Either, the example works:
`EitherAsync(async () => 5).chain(async (x) => Right(x + 1)).run()`

When I want to combine EitherAsync with a library that uses plain promises am I forced to wrap every call in `EitherAsync(...)`?

**Comment by gigobyte** [comment]
Oops, that may or may not have been a copy-paste error 😅 

> When I want to combine EitherAsync with a library that uses plain promises am I forced to wrap every call in EitherAsync(...)?

It's recommended to wrap the library instead, [see here](https://github.com/gigobyte/ts-react-express-starter/blob/main/server/src/infrastructure/Bcrypt.ts).

**Comment by mahulst** [comment]
Thanks for the quick response. 
We're using some generated code that's promise based. I will check if we can make some helper that makes it more convenient.
