### ISSUE TITLE
Allow passing `ReadonlyArray<T>` values where `T[]` is required

### ISSUE THREAD

**Issue by libre-man** [gigobyte/purify#420]
In quite some methods for `Maybe` and `Either` a `T[]` is expected, however this means a readonly array is not allowed. As all these methods don't mutate their input a more accurate type would be `ReadonlyArray<T>` (or `readonly T[]`).

**Comment by gigobyte** [comment]
`ReadonlyArray` is a bit of a pain the ass in TS, I avoid using it because it will conflict with everything constantly. Even if I add it to the signatures I'm not sure how much better the DX will be.

**Comment by ldlac** [comment]
Could function overloading be a nice to have in this case?

**Comment by gigobyte** [comment]
After playing around with it I don't really see a point in adding overloads, mainly because the `ReadonlyArray` is largely unusable in other libraries even after processing it with `Maybe/Either`.

**Comment by libre-man** [comment]
Would you be open for a new type `ReadonlyNonEmptyList` or something?

**Comment by gigobyte** [comment]
@libre-man Is this wanted because the `NonEmptyList` constructor doesn't accept readonly arrays?

**Comment by libre-man** [comment]
Yeah and because I sometimes want to make sure that the thing we pass around cannot be mutated, which a `NonEmptyList` can. Kind of the same as `ReadonlyArray` vs `Array`.

**Comment by libre-man** [comment]
Sorry for bugging about this again, but we have this issue in quite some places in our code (We use `vue` so passing around  frozen `ReadonlyArray`s  also has some performance benefits). Also passing in read only stuff makes it way easier for us to define clear API boundaries.

Would a type like `ReadonlyNonEmptyList` be accepted as a PR?

Also unrelated: is there a way for me to donate a small amount monthly for the use of the library? My company uses it quite a bit and I'd love to give a bit back.

**Comment by gigobyte** [comment]
If this issue is still important to you after almost 2 years I will do my best to come up with a solution, no PR is needed. 😅 I'll keep you posted in this issue.

Regarding the donation, I tried setting up GitHub Sponsors but it might take some time, my PayPal is s.iliev3@gmail.com, I believe recurring payments are easy to set up there. I've been working on this library for 5 years now and it's hard to the same motivation to maintain it as way back in the beginning so any financial support is greatly appreciated! 🙏

**Comment by KevinMGranger** [comment]
The solution should just involve adding `readonly` to the parameter declarations, and that's it! [You can see why it works in this playground link.](https://www.typescriptlang.org/play?#code/PTAEDMFcDsGMBcCWB7apoEMC2joHNQAHDeeAUwCdoAuUGWVAZwAoBBCvASmYCUz5IVTgChhDaI3ih4GRABsAspBkAjOWT4YAJqjkBPUAF5QAHgAqAGgB8zDBQq0zAbQC6nWhTLbdB5y9AAPuiQcnJGVqAA3sKgsaDikqBOABZeWhagAHTZMvL+xnYUANwxcZ4CVKDMqdpGhsYwWmTguGRanKAA-MGhoLS5ciUAvqIJUgNKquqTGGpkRqaWNoWOru6gfoE9YYYR0XHxTFIpaRnZmQP5oIUlB+WCaNVpdQ3QTS3QbR3d0CFh-bJBsIRmIjtJAZodNB9JCfAtzNZbPYPGk4X51p5vNDfK4tr9ersoqVYmMkjV0lkcoCrjdiaB7pUnrV6q93q12l1tn1wfJhqMwQNYdiZnN4UskQ56ajsRs1qt-EF8Ts9nTSSdtGcqXkFrS7vwHlVyS86G9muzvlyAbzgfyJFJMVD9GYAO7IFFY-TBLAqSi44xOACsGQAbC5QXbQFhlLN1C63V6fRQ-UlgxkAOxh4RQOBIVDXRiMSjwAByyBLf3MoDIAA9yG9GFKPQYMNA9K4bNXHHi-usMAWiw3q6BEA2AKLV2BySBNBHbFUHRDgKpDlnbDrwZIUZDOjZ6QhkUf2ZAUZgAIlgLYA5FIfdtTyIQSB4lepJBC43HQZwMfrpHo6K7DwDINxHYcGw3eZYEETxoCkEdGEgMhhHUV8sAoIUnUBBYJn-dQML0ZgHR8ONOBKYQnxUZRQD0ZBIGfNBiALX8oymeZ4GQa40EQLAWJjJCULoexJjMLDjEFaUYQkgjeLmEiinzQsKBLMtiz+ZhoOEwFSNEJ8AAltzIAA3SgMgAfQZaBcDwUzfyImVCgwAwLzQW94C3SA5kYZAsDICxyLAMhGH3WBEAwUIvx-BgsEIZBGEQXNoEycNEi8nyzGSRAKC0AAFOx4D0AAxegEoWZgZPUUyVgTX03HCIkDnKshKvsTJCDfZJmAARlI0AnxAhtGGSWi5C0UBbzCuQDK0G1-OHeBLwbaAy2uUIpqS1KyHSzKcrywripQaB1KE5QRPkbTZsouClxouiZAAa3mXAPzhFtRosv9WOuexHMYc5Zpu0A8H4aRUjGwKpGQJcVDLZJQFdCgRsYDJAuC0LwogSLvJiuKEoAQltRJnXioblAKzLJDjMVESquzPXReVuwJec4gEzwELkKQxIhKSRXUCVtIXJdCMCkJOfqNcpQqNAlTIg4n0YuL8A+vjQEMsLEPzYceNw+ZAMgHzYLpNnRew7mm15shhfZ+ABbKfVKmNjm+WSqQWPYCgFiJjdaPgMmKAp11habOSFKLUty1CMrlHd7SNq2rLcqUvacwOqP4BjkoEmQdRMkmvA0-dpwAAZ8nF7qyNJN37AAJk94mfb9gPkDTviQ77RTlIjuQC-sc644yhPdqKlPUB7ihtKznO87H4vS+McudLAAHnNAQt5kar6KB+zWWyrWsyAkA7QEh577O+vRfuEfL91Acc6y0RhZwAVQiYwzD3++Gyfzk3I12hwDCoWEo195gAA0Fh3wPg-EwLY2wuAyLTZsrZ2zAL3PMAAmhA-e9YTCIM4nAjIsCUFAA)

I'd be happy to throw a PR your way later.

**Comment by gigobyte** [comment]
@KevinMGranger Wow, you're right, I believe this wasn't the case before in older TypeScript versions? I tested adding `readonly` to the functions in `List` and everything compiled just fine.

I'm adding the readonly modifier right now and I'll publish a new version shortly.

I'm also waiting for approval on my GitHub Sponsors, once I get it set up I'll let you know.

**Comment by gigobyte** [comment]
@KevinMGranger GitHub Sponsors is live 🚀
