### ISSUE TITLE
Codec custom

### ISSUE THREAD

**Issue by piero-p** [gigobyte/purify#427]
Codec custom return when Left is string. Could be Nothing instead or a Generic define by ?

**Comment by gigobyte** [comment]
I don't understand what you're trying to ask.

**Comment by PieroProcessing** [comment]
the signature of Codec return an Either<string, t>. this limit the way i want to deal with left option if decode fail so it is possible to change it ?

**Comment by gigobyte** [comment]
No, the error can only be a string, but you can use [parseError](https://gigobyte.github.io/purify/utils/Codec#util-parseError) to turn the string into am object.
