### ISSUE TITLE
Decoding a maybe throws an error

### ISSUE THREAD

**Issue by mahulst** [gigobyte/purify#469]
When I try to decode a value that has a maybe, the decoder fails. Is this expected?

```
test('throw on decode maybe value', () => {
    const input = { key: Just('hello')};
    const decoder = Codec.interface({
        key: maybe(string)
    });

    const result = decoder.decode(input);
    
    expect(result.isRight()).toBe(true);
    
    // result = {
    //   __value: 'Problem with the value of property "key": Expected a string, but received an object with value "hello"',
    //   _: 'L',
    // }
})

**Comment by ldlac** [comment]
You are wrapping the "hello" string in the object Just. Message seems accurate.

https://gigobyte.github.io/purify/utils/Codec#instance-decode
`Takes a JSON value (i.e. a plain JS object) and runs the decode function the codec was constructed with. All of purify's built-in codecs return a descriptive error message in case the decode fails.`

`Just` should not be used as an input of `decode`.

**Comment by mahulst** [comment]
The message is accurate. But it works for all other decoders except `maybe`, and would be very convenient.
Our usecase is when we have two applications that are combined at runtime, so we want to validate messages when these applications are communicating.

The alternative is encoding all messages before sending them, but I was wondering if this is a common enough usecase to let a `Maybe` instance decode without an error?

**Comment by gigobyte** [comment]
`Codec` makes the assumption that the data to be decoded is a plain JSON object, it's not expected to work with objects that are not serializable. If you check the examples for `maybe` you'll see that it takes a normal JS value like `null` and `undefined` and decodes it into a `Maybe` object.

For your use case, I recommend either calling `maybe.encode` on your value before sending it for decoding on the other application, or writing a custom codec, something like this (pseudo-code, haven't tested it):
```
const MyMaybe = (codec) => Codec.custom({
    decode: (x) => Maybe.isMaybe(x) ? codec.decode(x.toJSON()) : Left('not a maybe'),
    encode: (x) => x
})
```
