### ISSUE TITLE
Additional monads for purify-ts i.e. `Reader<E, T>`

### ISSUE THREAD

**Issue by william-cohen** [gigobyte/purify#479]
Firstly, I have to say that the ergonomics of `purify-ts` are incredible, and `Either/EitherAsync` constructs go a long long way. Rather than neglecting languages features, as in some other FP TS libraries ( :wink: ), I love how purify embraces common TS syntax.
However, for more advanced business-domain use-cases, I think `purify-ts` could help promote FP patterns beyond solid error-handling. I want to take the time to suggest an addition, `Reader`, along with some motivation for adding it in. I do this in-lieu of an actual PR just to make sure my thinking is actually inline with the goals of the library before throwing a bunch of new code at @gigobyte. The purpose of this issue is to engage a discussion around "moar monads!" 

The [`Cats` Scala library](http://typelevel.org/cats/datatypes.html) has some cool APIs that I think translate well into the `purify-ts` style

I think additions to the monads that the library provides might be useful (provided they're documented at the same standard as the other `purify-ts` constructs).

## `Reader<E, T>`

The Reader monad is useful for cases where you want to pass some config around to a lot of functions. The Reader monad provides this fp way of dependency injection by giving you a lazy-evaluated wrapper around `(E) => T` with all the usual goodies that Monads provide, like map (for mapping `T => U`), and chain (`T => Reader<E, U>`, very useful for chaining computations that share a super-dependency)

Possible purify-ts interface for `Reader<E, T>`
```typescript
export interface Reader<E, T> {
  /** Creates a Reader instance from a given function   */
  static from<E, T>(f: (env: E) => T): Reader<E, T>

  /** Transforms the return type inside `this` with a given function. */
  map<U>(f: (value: T) => T2): Reader<E, U>

  /** Maps the return of `this` with a `Reader` function. */
  ap<U>(readerF: Reader<E, (value: T) => U>): Reader<E, U>

 /** Transforms `this` with a function that returns a `Reader`. Useful for chaining many computations that require a common dependancy */
  chain<E2 extends E, U>(f: (value: T) => Reader<E2, U>): Reader<E2, U>

  /** Runs the Reader with the passed environment E, returning the computed value */
  run(env: E): T

  // ...fanatasy-land interfaces 
  // ...
}

```

Possible purify-ts example:
Writing an express middleware for user management. (Obviously these functions would nee to be async but `AsyncReader<E, T>` is something I'd rather code than describe) 
```typescript
// UserManagement.ts
import UserRepo from './repositories/User'
import User from './models/User'
import { Reader } from 'purify-ts'

class UserManagement {
  loadUser(id: string): Reader<UserRepo, User> {
    return Reader.from((repo) => repo.findOne(id))
  }

  searchUsers(query: string): Reader<UserRepo, User[]> {
    return Reader.from((repo) => repo.findAll(query))
  }

  saveUser(user: User): Reader<UserRepo, boolean> {
    return Reader.from((repo) => repo.save(user))
  }

  deleteUser(user: User): Reader<UserRepo, boolean> {
    return Reader.from((repo) => repo.delete(user))
  }
}

export default new UserManagement()
```
```typescript
// main.ts
import UserRepo from './repositories/User'
import UserManagement from './UserManagement'
import { Reader } from 'purify-ts'

const app = express();
app.use(express.json());

const useUserManagementMiddleware = (userRepository: UserRepo) => {
  app.get("/users",  (req: Request, res: Response) =>  {
    UserManagement
      .searchUsers('*')
      .map(res.json)
      .run(userRepository)
    })

    app.post("/users", function(req: Request, res: Response) {
      UserManagement
        .saveUser(req.body)
        .map(res.send)
        .run(userRepository)
    })

   // ...
}

// ...
```

Other use-cases include state management on the front-end; monadic Redux or Vuex actions that can ship as part of an API client that provides direct composability into existing state management structures.

**Comment by gigobyte** [comment]
Hey, thanks for your suggestion, I've already expressed my opinion about `Reader` here: https://github.com/gigobyte/purify/issues/266

**Comment by william-cohen** [comment]
> Hey, thanks for your suggestion, I've already expressed my opinion about `Reader` here: #266

Fair enough. Feel free to close the issue
