### ISSUE TITLE
Either.encase should force the error to have the correct type

### ISSUE THREAD

**Issue by timvandam** [gigobyte/purify#494]
https://github.com/gigobyte/purify/blob/42b540208f8a5977498e92263b035125c792a358/src/Either.ts#L126-L132

Currently, it is possible to fill an `Either<Error, number>` with a Left(nonError), as whatever is thrown by the function supplied to Either.encase is just accepted. I think it would be good to offer an option that enforces this type. Something along these lines:
```ts
encase<L extends Error, R>(throwsF: () => R, leftClass: new () => L): Either<L, R> {
  try {
    return right(throwsF())
  } catch (e: unknown) {
    if (e instanceof leftClass) return left(e)
    throw new Error('Unknown error type was thrown')
  }
}
```

This strictness could become optional to prevent breaking changes. I for one would definitely use this

**Comment by gigobyte** [comment]
Unfortunately errors are not typed in TS so there's no point fighting the language. The same applies for all functions in `EitherAsync`, if you set the type to `EitherAsync<string, ...>` there's nothing stopping you from throwing a boolean and causing a runtime error.

The responsibility is on the developer to know what types of errors their code can throw (if there was a better way I would implement it but there's none to my knowledge).
