### ISSUE TITLE
Docs: EitherAsync.lefts has elements improperly borrowed from EitherAsync.rights

### ISSUE THREAD

**Issue by billwanjohi** [gigobyte/purify#502]
The docs for `EitherAsync.lefts` has a couple of problems:

1. The description looks to be copy-pasted from `EitherAsync.rights`
2. The example calls rights, not lefts (but outputs lefts)

> # EitherAsync
> ...
> ## Static methods
> ...
> ### [lefts](https://gigobyte.github.io/purify/adts/EitherAsync/#static-lefts)
> ...
> Takes a list of `EitherAsync`s and returns a Promise that will resolve with all `Right`…
> 
> | input                   | output                                                   |
> |-------------------------|----------------------------------------------------------|
> | EitherAsync.rights(...) | Promise {<resolved>: ['Server error', 'Wrong password']} |

Introduced [here](https://github.com/gigobyte/purify/commit/0cce56a24a50ff1779b7423a1c1665ad8f8b63e4#diff-a10c1963450b53c2812df1a879be3a7418d85aef4329cd6fc0cd4fa32be32512R1633-R1648)

**Comment by gigobyte** [comment]
That's correct, thanks for reporting and fixing the problem!
