### ISSUE TITLE
Type-safe compose function

### ISSUE THREAD

**Issue by klhex** [gigobyte/purify#520]
Hello,

Thanks for that nice library!

The docs say "There is no such function in purify! Unfortunately it's not possible to provide a type-safe version of compose and friends, so until TypeScript allows us to do that purify will not have them.".

However, according to some googled web pages, this could be possible:
- https://minaluke.medium.com/typescript-compose-function-b7512a7cc012
- https://gist.github.com/joshcox/d59bf241458cf456b49f3c5b098af9fa
- https://codewithstyle.info/TypeScript-3-4-hidden-gem-propagated-generic-type-arguments/
- https://www.npmjs.com/package/ts-functional-pipe

I'm by no means a Typescript pro but do the above sources mean it's possible to do it in TS nowadays and if so will a compose function make it into purify-ts?

**Comment by gigobyte** [comment]
Types for `compose` have improved during the years but they're still not perfect. Composing generic functions is a big hurdle that's still unsolved:

![image](https://user-images.githubusercontent.com/8791446/154840130-40afd06e-661b-4833-bfab-d9b289b427f3.png)
![image](https://user-images.githubusercontent.com/8791446/154840135-a6540977-0d51-4108-8405-0807037a5ad1.png)

**Comment by klhex** [comment]
I see, thanks for clarifying this to me, I hope that sooner or later Typescript will get there! 👍

**Comment by tulsidas** [comment]
[This implementation](https://github.com/MathisBullinger/froebel/blob/main/pipe.ts) seems sufficiently type-safe
