### ISSUE TITLE
`EitherAsync` `chain` causes error on nested `EitherAsync`

### ISSUE THREAD

**Issue by atomanyih** [gigobyte/purify#525]
[sandbox link](https://codesandbox.io/s/purify-ts-chain-unwrap-10r1fd?file=/src/index.ts)

Contrived example:

```ts
EitherAsync.liftEither(Right("unused"))
  .map((x) => EitherAsync.liftEither(Right("value")))
  .chain((c) => c)
  .run()
// The types say this is Promise<Either<never, string>>
// In actuality, at runtime it is a Left<TypeError> containing `promise.then is not a function`
```

In practice, this came up while using `.ap` to apply a function that returns `EitherAsync` to two `EitherAsync` arguments
```ts
function getHotdog(): EitherAsync<NoMoreHotdogsError, Hotdog> 

function getUser(): EitherAsync<NotHomeError, User>

function feedUserHotdog(
  hotdog: Hotdog,
  user: User
): EitherAsync<UserNotHungryError, User>

getUser()
  .ap(getHotdog().map(curry(feedUserHotdog)))
  .chain((x) => x)
  .run()
// at runtime, this errors in the same way
```

`.join` does not cause this error

Why am I using `.chain(x => x)` instead of `.join`?
`.chain` is typed to include the left-hand type of the returned `EitherAsync`, whereas `.join` discards it. The docs indicate that `.join` chould be equivalent to `.chain(x => x)`. See issue #526 

-------

For the last week I've been using this library and evaluating it for use in our prod app and have really appreciated its approachability and clear code examples. It has been much easier to learn than the brick wall of `fp-ts`!

However, I ran into a few problems that have prevented us from easily adopting it in our production code

**Comment by gigobyte** [comment]
This is now a type error

Fixed in v1.3.2
