### ISSUE TITLE
Extracting value from either

### ISSUE THREAD

**Issue by mustafaekim** [gigobyte/purify#54]
Hi,

Is there a way to extract value from the Either? (Both Left/Right)

I know should better not extract it but my server returns me an either, and now I need to return a simple json. how can I do the transformation? Through closure? That sounds very ugly

**Comment by gigobyte** [comment]
Hello!
There a couple of ways to do that:

#### 1. Imperative (please avoid using this)
```ts
const myEither = someOperation()

if (myEither.isLeft()) {
    return json
} else {
    return otherJson
}
```

#### 2. caseOf (also known as case analysis or catamorphism)
```ts
const myEither = someOperation()

return myEither.caseOf({
   Left: err => json
   Right: value => otherJson
})
```

There are also methods that are for specific use cases:

#### 3. orDefault (when you don't care about the error)
```ts
const myEither = someOperation()

return myEither.orDefault(someErrorJson) // returns error json when Left or the value inside if Right
```

Hope that helps!

**Comment by mustafaekim** [comment]
Thanks but the json is inside the either

**Comment by gigobyte** [comment]
When you use `caseOf` you have access to the value inside the either. For example:

```ts
const e = Right({data: 'somedata'})

e.caseOf({
    Left: _ => res.status(500),
    Right: json => res.send(json) /* json variable here is the data inside Right */
})
```

**Comment by mustafaekim** [comment]
Yes, thanks, but still I cannot return the json value. I have to return it unfortunately

**Comment by mustafaekim** [comment]
Below is the code I am using right now

```ts

export const getEmailEvents = functions.https.onRequest(async (req, res): SR<Email> => {

    if (!validateGetEmailEvents(req.body)) {
        return NOK(res, ServerError.invalidBody)
    }
    try {
        var tokenObject = await getTokenObject(req.body.token);
        allowAnyRole(tokenObject, ["ADMIN", "MANAGER", "OPERATOR", "EDITOR"]);

        var resp: ZetResponse<Email, any>;
        var either = await service.email.get(req.body.emailId);
        either.mapLeft((err: ZetError) => {
            resp = NOK(res, ServerError.notFound)
        }).map(async (doc: Doc<Email>) => {
            doc = await service.email.updateEventsForEmail(doc)
            resp = OK(res, bZetOK(doc.data as Email))
        })
        return resp;
    } catch (err) {
        return ERROR(res, err)
    }

});
``

**Comment by mustafaekim** [comment]
Oh, there is **.extract()** ! I didnt know it existed. Is that the way I should go?

**Comment by gigobyte** [comment]
I can't see why you can't do
```ts
return either.caseOf({
    Left: _ => NOK(res, ServerError.notFound),
    Right:  doc => OK(res, bZetOK(doc.data as Email))
})
```
which is almost like what you're doing but without the mutation. Also I don't think the `async/await` in your `map(async (doc: Doc<Email>) ` works like you would expect it to.

**Comment by mustafaekim** [comment]
I didn't know & expect that caseOf returns any value but still typescript complains that types do not match on Right.

`Type 'ZetOK<Email>' is not assignable to type 'ZetError<any>'.`

Another problem is that caseOf's branches Left/Right may not work promises. Do they?

Moreover you say that map & mapLeft would not also work as I would expect, so what do you recommend me in this case? Shouldn't I use Either?

**Comment by mustafaekim** [comment]
Would you think that the code below would work as I would expect ?

```ts
export const getEmailEvents = functions.https.onRequest(async (req, res): SR<Email> => {

    if (!validateGetEmailEvents(req.body)) {
        return NOK(res, ServerError.invalidBody)
    }
    try {
        var tokenObject = await getTokenObject(req.body.token);
        allowAnyRole(tokenObject, ["ADMIN", "MANAGER", "OPERATOR", "EDITOR"]);
        var either = await service.email.get(req.body.emailId);
        return await (either
            .mapLeft((err: ZetError) => NOK(res, ServerError.notFound))
            .map(async (doc: Doc<Email>) => {
                doc = await service.email.updateEventsForEmail(doc)
                return OK(res, bZetOK(doc.data as Email))
            })
            .extract())
            
    } catch (err) {
        return ERROR(res, err)
    }

});
```

**Comment by gigobyte** [comment]
I cannot confirm that it will work, but on first glance it seems correct. Keep in mind `extract` will turn a `Either<A, B>` into a `A | B` TypeScript union type.
