### ISSUE TITLE
Enable consumption from Typescript when `moduleResolution` is `Node16`

### ISSUE THREAD

**Issue by Duncan3142** [gigobyte/purify#556]
Hi,

Thanks for this brilliant library. It's the first time I've tried functional error handling, liberal use of `Either` is making my code feel much cleaner.

I've encountered an issue using purify-ts with both the latest version of Typescript and Rollup in general. I believe both issues share the same root cause. 

Typescript 4.7 supports `Node16` as it's `module` output target. This in turn will set `moduleResolution` to be `Node16`. Under these conditions, packages without an `export` object in `package.json` cannot be reliably consumed.

Adding the following to `package.json` will allow purify-ts modules to be consumed correctly.
Node versions that don't support the `exports` object fallback to the `main` field as usual.

```
"exports": {
  ".": {
    "import": {
      "types": "./es/index.d.ts",
      "default": "./es/index.js"
    },
    "require": {
      "types": "./index.d.ts",
      "default": "./index.js"
    }
  },
  "./*": {
    "import": {
      "types": "./es/*.d.ts",
      "default": "./es/*.js"
    },
    "require": {
      "types": "./*.d.ts",
      "default": "./*.js"
    }
  }
}
```

See the following links for more information:
[Typescript 4.7 Blog Post](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#package-json-exports-imports-and-self-referencing)
[Node package docs](https://nodejs.org/api/packages.html#package-entry-points)

**Comment by Duncan3142** [comment]
To add some context, this isn't an issue if you use `import Either from 'purify-ts'`.
The problem occurs when you try to `import Either from 'purify-ts/Either'` or `import Either from 'purify-ts/es/Either'`.

**Comment by gigobyte** [comment]
Thank you for your contribution. I'll try to implement and test out the changes soon.
