### ISSUE TITLE
Mistake in Maybe documentation example?

### ISSUE THREAD

**Issue by filidorwiese** [gigobyte/purify#570]
On https://gigobyte.github.io/purify/adts/Maybe/ the following example is given:

```
const port = getConfig()
    .chain(x => x.port)
    .map(parseInt)
    .orDefault(8080)
```

Although it's not fully clear what the hypothetical `getConfig()` method returns, the non-Maybe example suggests that it is probably a plain object with an optional `port` property:

```
const port = parseInt(getConfig()?.port ?? '8080')
```

Should the Maybe-equivalent example then not be:

```
const port = Maybe.of(getConfig())
    .chainNullable(x => x.port)
    .map(parseInt)
    .orDefault(8080)
```

instead?

**Comment by gigobyte** [comment]
The `With Maybe` example implies that Maybe is used within the whole project, so `getConfig` would return a `Maybe<Confg>`. It could be made more clear but the example is for demonstration purposes only.

I don't know, I'll close this issue but if anyone else is reading this and feels the same way please leave a comment, I might reconsider the examples.

**Comment by filidorwiese** [comment]
Thanks for the super quick reply. I can understand `getConfig()` returning a `Maybe` making the `Maybe.of()` superfluous. But even then the `.chainNullable` addition would be more accurate. It seems unlikely to me that each property in the `getConfig()` Maybe is wrapped in a Maybe itself.

Anyways, it's your call, it just confused me today. Keep up the good work :+1:
