### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by ceigey** [gigobyte/purify#59]
I was wondering if there was a roadmap, even if vague and/or previously unwritten, for this library?

The API and explanations in the docs so far look great so far. Even though I am not currently using TypeScript, this library seems like one I would adopt (in the untyped JS world, I have adopted Sanctuary).

However, the following is unclear:
* What are the future goals of the library?
* Is this library considered finished?
* Is this library intended to be part of a ecosystem of likeminded libraries or handle additional functionality itself?
* What should future contributors focus on?

But by all means, if you are satisfied with the current state of the library, that's cool too - I can see a lot of the essentials are already in place. All I can think of are things like typesafe pipes (which I hear are a challenge in TypeScript, and safe record property access, and that's more niche and perhaps better served in a standalone JSON handling library).

(also, thank you for writing this library. It got me interested in fluent functional APIs again!)

**Comment by gigobyte** [comment]
Thanks for bringing it up, I appreciate all of the feedback I receive!

I have a roadmap for the project, but it's not something that I've written down. I'll make sure to address your questions, I hope you don't mind me using your questions as part of something like a FAQ for the project?

**Comment by gigobyte** [comment]
The roadmap is done, I will deploy it as part of the next release.

**Comment by ceigey** [comment]
Awesome, thanks for the update!

**Comment by ceigey** [comment]
Just read the FAQ in master (`e81a7e0`), looks great! Looking forward to some of the planned features!
