### ISSUE TITLE
Improve site SEO

### ISSUE THREAD

**Issue by gigobyte** [gigobyte/purify#6]

**Comment by chrismcleod** [comment]
Pure TS in google brings up a whole lot of shemale porn which I have accidentally clicked a few times looking for this lol.

**Comment by gigobyte** [comment]
Yeah I know about that :disappointed_relieved: :disappointed_relieved:

**Comment by gigobyte** [comment]
I agree, it's just that I still haven't decided on what to replace it with. I really want to keep the `pure` name but `pure-typescript` is taken.

**Comment by gigobyte** [comment]
I've decided on renaming the library to `purify`. Next week will be a new release that goes with the new name, the package will be `purify-ts`
