### ISSUE TITLE
Chain with async function

### ISSUE THREAD

**Issue by mustafaekim** [gigobyte/purify#60]
Does chain accept an async function? I didn't understand if my code is broken or that chain does not accept async function..

The code that I want to improve via chain is as below. As far as I understand, I should use chain instead of map to eliminate the extract() function all over the code

```ts
    var either = await service.form.getFormInstance(req.body.formInstanceId)
    return either
        .map(async (doc: Doc<FormInstance>) => {
            var either = await getTokenObjectValidForFormInstance(req.body.token, doc.data)
            return either
                .map((tokenObject: OrganizationTokenObject | RoomTokenObject) => {
                    return OK(res, bZetOK<FormInstance>(doc.data))
                }).extract() // ???
        })
        .mapLeft((err: ZetError) => ERROR(res, err))
        .extract()
```

**Comment by mustafaekim** [comment]
I realise that this code is completely broken because even if the either inside map returns a left, I cannot catch it in mapLeft. So I certainly need a replacement with chain

**Comment by mustafaekim** [comment]
**Any idea on how I can pass an async function into a chain?** I cannot transform an Either to another Either asynchronously.

**Comment by gigobyte** [comment]
Promise and Either are both monads, and monads do not compose. Unfortunately, there's no easy way to do what you're trying to do in the context of this library, but I see that there is a problem and I'll try to address that in the next version of purify.

**Comment by mustafaekim** [comment]
Oh ok, I will write a utility function to do that. Thanks

**Comment by gigobyte** [comment]
Here's an example API that I'm thinking about (this is just a draft):
```ts
async function run() {
  const either = await getFormInstance()
  const data = await either.chainAsync(doc => getTokenObjectValidForFormInstance(doc.data))

  return data
    .map(tokenObject => OK(tokenObject))
    .mapLeft(err => ERROR(err)).extract()
}
```

**Comment by mustafaekim** [comment]
Yes exactly but I was planning to build --just as an external utility function

chainAsync will be perfect.

**Comment by mustafaekim** [comment]
Hi, is there any guess on when you will implement, I would prefer to use the library method

**Comment by gigobyte** [comment]
After giving it some thought I really don't like the way mapAsync and chainAsync work currently. I'll be researching other ways to accomplish an elegant async API.

**Comment by mustafaekim** [comment]
OK. I have to drop the library because I cannot advance in the current situation.. That will cause a lot of work to be redone but it seems like there is no easy solution for now. Without chain, the only solution left is to use unsafeCoerce and catch the error, which makes the code very ugly.

It would be OK to have chain accepting an async function even though it returns a promise of either. I am using map in the same manner.

**Comment by mustafaekim** [comment]
below is how I try to handle multiple async calls

```ts
  try {
    var organizationDoc = (await service.organization.get(body.organizationId)).unsafeCoerce()
    if (!organizationDoc.data.settings.signUp.allow) return NOK(res, ServerError.somethingIsWrong)

    var either = await service.organization.addUser(body.organizationId, body.fullname, body.username, body.password, organizationDoc.data.settings.signUp.tags, body.email);
    return either
      .map(async (doc: Doc<User>) => {
        var userCard: Card = await service.authentication.createUserCard(body.organizationId, doc);
        return OK(res, bZetOK<Card>(userCard));
      })
      .mapLeft((err: ZetError) => NOK(res, err))
      .extract()
  }
  catch (err) {
    return ERROR(res, err);
  }
```

**Comment by gigobyte** [comment]
Sorry for causing you to rewrite your code, as you can see the library is still in early development and there are a lot of important decisions ahead and I don't want to rush these things. 

Your code is can be easily refactored to better functional code though. From my observations you're trying to mix imperative if statements, async/await, early returns and purely functional programming, which leads to confusion and messy code. Here's how I would write your implementation with the current version of purify:

```ts
return (await service.organization.get(body.organizationId)
  .then(eitherOrganizationDoc =>
    eitherOrganizationDoc
      .filter(x => x.data.settings.signUp.allow)
      .mapLeft(_ => NOK(res, ServerError.somethingIsWrong))
      .map(organizationDoc => service.organization.addUser(/* params */))
  ).then(either =>
    either
      .map(doc => service.authentication.createUserCard(body.organizationId, doc))
      .mapLeft((err: ZetError) => NOK(res, err))
  )).extract()

```

**Comment by gigobyte** [comment]
Sorry for causing you to rewrite your code, as you can see the library is still in early development and there are a lot of important decisions ahead and I don't want to rush these things.

**Comment by gigobyte** [comment]
I spend some time analyzing your code and I see a couple of problems. You really shouldn't try to mix imperative if statements, async/await and early returns, it's not going to work. I did some refactoring and here's how I would write this code:

```ts
const isSignUpAllowed = (doc: Doc): Either<ServerError, Doc> =>
  doc.allow ? Right(doc) : Left(ServerError.somethhingIsWrong)

serviceOrganizationGet().then(organizationDoc =>
  organizationDoc
    .chain(x => isSignUpAllowed(x))
    .map(doc => addUser(doc.tags))
    .map(userPromise =>
      userPromise
        .then(user => createUserCard(user))
        .then(userCard => bZetOK(userCard))
    )
    .mapLeft(err => NOK(err))
    .extract()
)
```

Please let me know if that helps!

**Comment by mustafaekim** [comment]
What if map(userPromise) fails? I end up with a Left inside a Right situation, no? If so, it will bypass the mapLeft that follows.

**Comment by gigobyte** [comment]
Good question! I guess I didn't test this enough. I'll close this topic as we're getting off topic now, as I said I'll give it some thought and I'll avoid posting more not working code :sweat_smile:
