### ISSUE TITLE
Add ES modules in the npm package

### ISSUE THREAD

**Issue by semmel** [gigobyte/purify#604]
For the benefit of JavaScript users, please consider to compile to ES modules for distribution via npm.
What I mean is essentially the same what has been attempted in #293 , which was later reverted. 

Would you consider ES2020 output as *third build target* and include that in npm publish?
If not, could you explain why keep distributing an ES5 output while those runtimes (IE, old Node) should be gone by now?

Background:
- De-facto module loader for browser environment
- Bundler-free development in the browser is possible with ES modules, bare import specifiers can be overcome with import-maps (now a [WhatWG standard](https://wicg.github.io/import-maps/))

**Comment by gigobyte** [comment]
Hi! I'm fine with a third output target but as far as I can remember the blocker for that issue was that you need to add `"type": "module"` to package.json which would break all other outputs.

What do you think?

**Comment by semmel** [comment]
I'll give it a try without `type: "module"`…

**Comment by semmel** [comment]
@gigobyte Could you review PR #605 ?

**Comment by gigobyte** [comment]
Available in `1.3.0`
