### ISSUE TITLE
[feature request] Add IO monad

### ISSUE THREAD

**Issue by leohxj** [gigobyte/purify#611]
Here is `MaybeAsync`, and `EitherAsync` to process async values.
But how can I process with normal side effect function, such as read from localStorage, read dom element, etc...

IO monad same like a better way to adapt those cases. Why not purify add the new `IO` API ? 

thanks gigobyte.

**Comment by gigobyte** [comment]
Ask yourself what you're getting out of that feature. Does it help you with separating pure from inpure code when there are no compiler guarantees and when all of the other libraries (including the standard one) are not using this `IO` monad?

In my opinion, if you really want something like `IO` just prefix your function with `async`, you get the same result and you get all of the already available tooling like async/await, promise libraries etc
