### ISSUE TITLE
Crashes because of use of `JSON.stringify` in Codec module

### ISSUE THREAD

**Issue by olmokramer** [gigobyte/purify#614]
The `reportError` function in the Codec module uses `JSON.stringify` in the `case 'object'` branch to turn objects into a string for display. This can cause errors to be thrown, though, if the `input` object contains values that are not `JSON.stringify`able, such as `BigInt`.

**Example**

```typescript
import * as codec from 'purify-ts/Codec';

const myCodec = codec.Codec.interface({ n: codec.string, d: codec.string });
console.log(myCodec.decode({ frac: { n: BigInt(1), d: BigInt(1) } }));
```

**Expected** `Left('Problem with property "n": it does not exist in received object "..."')`

**Actual** An error "Do not know how to serialize a BigInt" was thrown on the `console.log(...)` line.

**Comment by olmokramer** [comment]
Thank you for the quick fix! Unfortunately I am still able to reproduce the bug, though. It seems [`reportError`](https://github.com/gigobyte/purify/blob/ea62f0af124d6376cc08cf693b51eb64e7339613/src/Codec.ts#L33-L70) is still using `JSON.stringify` without the [`replacer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#parameters) argument.

Here are some reproducing examples:

```
$ pnpm install purify-ts@1.3.1
Packages: +2
++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/olmo/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ purify-ts 1.3.1

Progress: resolved 2, reused 1, downloaded 1, added 2, done
Done in 1.8s

$ node
> p = require('purify-ts')
> p.string.decode({ n: BigInt(3) })
Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at reportError (/home/olmo/codegrade/tmp/purify/node_modules/.pnpm/purify-ts@1.3.1/node_modules/purify-ts/Codec.js:73:58)
    at Object.decode (/home/olmo/codegrade/tmp/purify/node_modules/.pnpm/purify-ts@1.3.1/node_modules/purify-ts/Codec.js:213:34)
> p.string.decode([ BigInt(3) ])
Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at reportError (/home/olmo/codegrade/tmp/purify/node_modules/.pnpm/purify-ts@1.3.1/node_modules/purify-ts/Codec.js:72:57)
    at Object.decode (/home/olmo/codegrade/tmp/purify/node_modules/.pnpm/purify-ts@1.3.1/node_modules/purify-ts/Codec.js:213:34)
```

**Comment by gigobyte** [comment]
Oof, I tested it without an object wrapping the BigInt and thought this error only happened with `Codec.interface`. Looks like I'll have to replace all instances of `JSON.stringify` in Codec.

**Comment by olmokramer** [comment]
Thanks again for the fix! Can confirm it works now for my use cases.
