### ISSUE TITLE
Make Pattern Follow TypeScript Naming Scheme

### ISSUE THREAD

**Issue by czhang03** [gigobyte/purify#626]
Hi I noticed most of the pattern here (`EitherPattern`, `MaybePattern`, etc) follows haskell style naming scheme. However by default TypeScript recommend to use camelCase for fields in an object. 

I was wondering it is possble to create a overloaded version of `caseOf` that use naming scheme that is recommended by TypeScript, like:
```
someMaybe.caseOf({
  nothing: () => ...
  just: (val) => ...
})
```

**Comment by czhang03** [comment]
Sorry, I should have mentioned the use case the this. I use eslint with my project, hence I need to silence all the lines with caseOf if I want to enforce the naming scheme.

There is no good way around it, as I cannot simply disable or change the recommended rule, since I do want my other classes to have consistent naming.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by czhang03** [comment]
But I guess I can always just modify the prototype in my own project if you are not happy with this change.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gigobyte** [comment]
Yes, of course, you can use the information in this thread on how to extend/modify the modules: https://github.com/gigobyte/purify/issues/623
