### ISSUE TITLE
please clarify deno support

### ISSUE THREAD

**Issue by scarf005** [gigobyte/purify#641]
hello, thanks for the library. I've been using purify in deno with no problem, 
```ts
import { Either, Left, Right } from "npm:purify-ts/Either"
```
however the [deno module](https://deno.land/x/purify@v0.11) is outdated (3Y). could you either deprecate it or update to latest version? thank you for your time.

**Comment by gigobyte** [comment]
The deno module is not created or maintained by me, it was created by another user so I don't have any control over it.

**Comment by scarf005** [comment]
i see. thanks for the clarification.
