### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by emastho** [gigobyte/purify#644]
I wanted to ask if you, dear developers, could invest some time into creating a discord for the library (or want me to setup it for you).
I think this library has the most developer friendly DX which is amazing for those who are still learning functional programming. 
It would be a good place to find help, other libraries like fp-ts already have it.

**Comment by gigobyte** [comment]
The purify-ts community is pretty much nonexistent, I'm afraid the discord won't be active at all. I also don't frequent FP discords/slacks etc so I wouldn't be able to help out people reaching out for help.
