### ISSUE TITLE
widen output types for `Maybe.mapOrDefault`

### ISSUE THREAD

**Issue by scarf005** [gigobyte/purify#652]
hi, thanks for the cool library. that is, widening output type for `Maybe.mapOrDefault` would be more ergonomic to use, considering it's used to unwrap values inside Maybe.

```ts
interface Maybe<T> {
  mapOrDefault<U, V>(f: (value: T) => U, defaultValue: V): U | V
}
class Nothing implements Maybe<never> {
  mapOrDefault<U, V>(_: (value: never) => U, defaultValue: V): V {
    return defaultValue
  }
}
class Just<T> implements Maybe<T> {
  constructor(private readonly value: T) {}

  mapOrDefault<U, V>(f: (value: T) => U, _: V): U {
    return f(this.value)
  }
}

const match = (value: Maybe<number>) => value.mapOrDefault((x) => x + 1, "not a number")
// previously: value.mapOrDefault<number, "not a number">( /* ... */ )

const res1 = new Just(1).mapOrDefault((x) => x + 1, -999)
    // number
const res2 = new Nothing().mapOrDefault((x) => x + 1, -999)
    // -999
const res3 = match(new Just(1))
    // number | "not a number"
const res4 = match(new Nothing())
    // number | "not a number"

console.log([res1, res2, res3, res4])

```

[Playground Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLJwJ4CMIB4AqAfMgN4BQyyAtnAA4DyUAIhPAK4A2YuAqgDTIAaoQAUMAFzIRANzgc2ESfgCUyALzF+yACas4nMILkLJg5ZJ7IAPkLIBfMgg5wAzi+QA5APZgAFqABzZGAqWg4IKghwd3RsPBAIaWhickoaBmY9A14BYREAfUkZY0VkBKSoVQ1kLV12LiN5UrNTUgpKZCgIMDYoEB0shpL2hwcnV3cAKTYXbiJg0PDI6LRMHAIU9oQvEFmoNgQwLygRWihgWUhOiDhtHY4MZFkmpVUSB3b0xhZ67i08iRSZ4mZAqdSaASFITmGptDrXHp9ZAwER+YAuAB0wIgyhG9jIjh2s2ocDACF86iBJUksXWIDYVBwUEIVWI2IxX0yvxEIgAHqzkLzkABqZAARgEACIQD5kHAygymZLcQB6FXIM6JYBeGYPSTszk-fRcXD0xnQKUysByhXmqCS0TIFUAKmQGPdyGd6txhN21q6LjFlISAHdkNNZiIxcoOXRvoMwDz+eDBSLxQIALQAThzuPhauQAD0APy+4kBgBMwYgYe8aJAAREMcNCaTAqFoolyGzufalALJbL-ogLgAzJSaGTfCJQ+GZono3mOgPS9s-dcXAAWCek8kzmueHz+BtNpf99WDtcuLzhDEcLyNgDaAa7lYEAdH75Hm4AurigA)

haskell equivalent (used sum types as haskell doesn't support union types):

```hs
λ> data MyNum a = N a | NotNum deriving (Eq, Show)

λ> maybe NotNum (\x -> N x) (Just 3)
N 3
it :: Num a => MyNum a

λ> maybe NotNum (\x -> N x) Nothing
NotNum
it :: MyNum a
```

I'm interested in opening a pull request if the idea is accepted.

**Comment by gigobyte** [comment]
The power of `mapOrDefault` is that it checks if the default has the same type, so I don't like this change. If anyone wants this behaviour I would recommend `maybe.unwrap() ?? default` instead.
