### ISSUE TITLE
Maybe interopability with Tuple

### ISSUE THREAD

**Issue by SamHH** [gigobyte/purify#68]
Hey! So, it's only been a few hours but I love this project.

One pain point for me so far has been how to handle a tuple of maybes. For example, imagine a function that returns an object with optional properties. I'm interested in two of these properties. What I'd ideally like in my mind is to be able to form a sort of MaybeTuple.fromNullable, or something along those lines. Instead I ended up with the following which works but feels quite unergonomic:

```typescript
maybeThing
    .chain(thing => thing.propA && thing.propB
        ? Just(Tuple(thing.propA, thing.propB))
        : Nothing,
    )
    .ifJust(([first, second]) => {
        doSomething(first, second);
    });
```

In my mind I'm thinking something like this for the chain:

```typescript
    .chain(thing => MaybeTuple.fromNullable(thing.propA, thing.propB))
```
Which would return `MaybeTuple<typeof thing.propA, typeof thing.propB>`, basically a melding of Maybe and Tuple. It's only `Just` if both arguments pass the not nullable check.

Thoughts?

**Comment by gigobyte** [comment]
I'm glad you're enjoying purify. What you're interested in is extremely specific, I believe it would be best if you just implemented it as a helper inside your codebase:
```typescript
const MaybeTuple = {
  fromNullable<F, S>(fst: F | null | undefined, snd: S | null | undefined): Maybe<Tuple<F, S>> {
    return fst != null && snd != null 
        ? Just(Tuple(fst, snd))
        : Nothing
  }
}
```

**Comment by SamHH** [comment]
Works beautifully, thank you :+1:
