### ISSUE TITLE
Typescript 5.5 types behave poorly

### ISSUE THREAD

**Issue by stijnveenman** [gigobyte/purify#711]
Since typescript 5.5, type inference has been improved. This update affected purify-ts type inference in annoying ways. Previously, the following examples used to work

```ts
import {Maybe} from 'purify-ts';

const foo = (bar: Maybe<number>) => {
    return bar;
}

console.log(foo(Maybe.zero()));
                ^^^^^^^^^^^^^
Argument of type 'Nothing' is not assignable to parameter of type 'Maybe<number>'.
  Types of property 'isJust' are incompatible.
    Type '() => boolean' is not assignable to type '() => this is AlwaysJust'.
      Signature '(): boolean' must be a type predicate.(2345)

```

```ts
import {Nothing, Just} from 'purify-ts';

export const foo = (a: number) => {
             ^^^
Exported variable 'foo' has or is using name 'AlwaysJust' from external module "file:///node_modules/purify-ts/Maybe" but cannot be named.(4023)
Property '__value' of exported class expression may not be private or protected.(4094)

    return a ? Nothing : Just(5)
}

```

**Comment by valpinkman** [comment]
It seems the repo has been updated to use Typescript 5.5.2 about two weeks ago. Any chance to see a new release soon ?

**Comment by gigobyte** [comment]
The packages are automatically updated by renovate so it does not imply any compatibility unless there is a release with the updated packages. I'll get to investigating the bug this weekend.

**Comment by valpinkman** [comment]
@gigobyte thank you very much 🙏

**Comment by gigobyte** [comment]
Test pass for 2.1.0 on my machine, please try it out and close the issue if it's not reproducible anymore.

**Comment by valpinkman** [comment]
Thanks will try and report

**Comment by valpinkman** [comment]
Works on our side 👍

**Comment by stijnveenman** [comment]
We have now been able to update as well, thanks for the quick fix 👍
