### ISSUE TITLE
add some List functions?

### ISSUE THREAD

**Issue by kalxd** [gigobyte/purify#715]
I find there are some usefull functions for both `List` and `NotEmptyList`, such as:

```typescript
// The partition function takes a predicate and a list, and returns the pair of lists of elements which do and do not satisfy the predicate
const partition = <T>(predicate: (item: T) => boolean, xs: List<T>): [List<T>, List<T>];

// takeWhile applied to a predicate p and a list xs, returns the longest prefix (possibly empty) of xs of elements that satisfy p.
const takeWhile = <T> (p: (item: T) => boolean, xs: List<T>): List<T>;
```

so would you implement more about such functions on `List`?
or do you need a PR?

**Comment by gigobyte** [comment]
Purify only includes Array helpers that benefit from types like `Maybe`, for general purpose helpers there are tons of other specialized libraries that would do just as well and even better, honestly
